/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.shield.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ShieldCustomerType
 */
@JsonPropertyOrder({
  ShieldCustomerType.JSON_PROPERTY_ID,
  ShieldCustomerType.JSON_PROPERTY_USER_ID,
  ShieldCustomerType.JSON_PROPERTY_CUSTOM_ID,
  ShieldCustomerType.JSON_PROPERTY_HIT_POLICY,
  ShieldCustomerType.JSON_PROPERTY_IP_LIST,
  ShieldCustomerType.JSON_PROPERTY_DEVICE_TYPE,
  ShieldCustomerType.JSON_PROPERTY_SHIELD_TYPE,
  ShieldCustomerType.JSON_PROPERTY_SHIELD_NUM,
  ShieldCustomerType.JSON_PROPERTY_IDENTITY_USER,
  ShieldCustomerType.JSON_PROPERTY_IDENTITY_SYSTEM,
  ShieldCustomerType.JSON_PROPERTY_ADD_TIME,
  ShieldCustomerType.JSON_PROPERTY_MOD_TIME
})
@JsonTypeName("ShieldCustomerType")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ShieldCustomerType {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  private Long userId;

  public static final String JSON_PROPERTY_CUSTOM_ID = "customId";
  private String customId;

  public static final String JSON_PROPERTY_HIT_POLICY = "hitPolicy";
  private String hitPolicy;

  public static final String JSON_PROPERTY_IP_LIST = "ipList";
  private String ipList;

  public static final String JSON_PROPERTY_DEVICE_TYPE = "deviceType";
  private Integer deviceType;

  public static final String JSON_PROPERTY_SHIELD_TYPE = "shieldType";
  private Integer shieldType;

  public static final String JSON_PROPERTY_SHIELD_NUM = "shieldNum";
  private Long shieldNum;

  public static final String JSON_PROPERTY_IDENTITY_USER = "identityUser";
  private String identityUser;

  public static final String JSON_PROPERTY_IDENTITY_SYSTEM = "identitySystem";
  private String identitySystem;

  public static final String JSON_PROPERTY_ADD_TIME = "addTime";
  private String addTime;

  public static final String JSON_PROPERTY_MOD_TIME = "modTime";
  private String modTime;

  public ShieldCustomerType() { 
  }

  public ShieldCustomerType id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public ShieldCustomerType userId(Long userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(Long userId) {
    this.userId = userId;
  }


  public ShieldCustomerType customId(String customId) {
    
    this.customId = customId;
    return this;
  }

   /**
   * Get customId
   * @return customId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomId() {
    return customId;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomId(String customId) {
    this.customId = customId;
  }


  public ShieldCustomerType hitPolicy(String hitPolicy) {
    
    this.hitPolicy = hitPolicy;
    return this;
  }

   /**
   * Get hitPolicy
   * @return hitPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HIT_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHitPolicy() {
    return hitPolicy;
  }


  @JsonProperty(JSON_PROPERTY_HIT_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHitPolicy(String hitPolicy) {
    this.hitPolicy = hitPolicy;
  }


  public ShieldCustomerType ipList(String ipList) {
    
    this.ipList = ipList;
    return this;
  }

   /**
   * Get ipList
   * @return ipList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IP_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIpList() {
    return ipList;
  }


  @JsonProperty(JSON_PROPERTY_IP_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpList(String ipList) {
    this.ipList = ipList;
  }


  public ShieldCustomerType deviceType(Integer deviceType) {
    
    this.deviceType = deviceType;
    return this;
  }

   /**
   * Get deviceType
   * @return deviceType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DEVICE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDeviceType() {
    return deviceType;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceType(Integer deviceType) {
    this.deviceType = deviceType;
  }


  public ShieldCustomerType shieldType(Integer shieldType) {
    
    this.shieldType = shieldType;
    return this;
  }

   /**
   * Get shieldType
   * @return shieldType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHIELD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getShieldType() {
    return shieldType;
  }


  @JsonProperty(JSON_PROPERTY_SHIELD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShieldType(Integer shieldType) {
    this.shieldType = shieldType;
  }


  public ShieldCustomerType shieldNum(Long shieldNum) {
    
    this.shieldNum = shieldNum;
    return this;
  }

   /**
   * Get shieldNum
   * @return shieldNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHIELD_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getShieldNum() {
    return shieldNum;
  }


  @JsonProperty(JSON_PROPERTY_SHIELD_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShieldNum(Long shieldNum) {
    this.shieldNum = shieldNum;
  }


  public ShieldCustomerType identityUser(String identityUser) {
    
    this.identityUser = identityUser;
    return this;
  }

   /**
   * Get identityUser
   * @return identityUser
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IDENTITY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentityUser() {
    return identityUser;
  }


  @JsonProperty(JSON_PROPERTY_IDENTITY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentityUser(String identityUser) {
    this.identityUser = identityUser;
  }


  public ShieldCustomerType identitySystem(String identitySystem) {
    
    this.identitySystem = identitySystem;
    return this;
  }

   /**
   * Get identitySystem
   * @return identitySystem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IDENTITY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentitySystem() {
    return identitySystem;
  }


  @JsonProperty(JSON_PROPERTY_IDENTITY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentitySystem(String identitySystem) {
    this.identitySystem = identitySystem;
  }


  public ShieldCustomerType addTime(String addTime) {
    
    this.addTime = addTime;
    return this;
  }

   /**
   * Get addTime
   * @return addTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddTime() {
    return addTime;
  }


  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddTime(String addTime) {
    this.addTime = addTime;
  }


  public ShieldCustomerType modTime(String modTime) {
    
    this.modTime = modTime;
    return this;
  }

   /**
   * Get modTime
   * @return modTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MOD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModTime() {
    return modTime;
  }


  @JsonProperty(JSON_PROPERTY_MOD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModTime(String modTime) {
    this.modTime = modTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShieldCustomerType shieldCustomerType = (ShieldCustomerType) o;
    return Objects.equals(this.id, shieldCustomerType.id) &&
        Objects.equals(this.userId, shieldCustomerType.userId) &&
        Objects.equals(this.customId, shieldCustomerType.customId) &&
        Objects.equals(this.hitPolicy, shieldCustomerType.hitPolicy) &&
        Objects.equals(this.ipList, shieldCustomerType.ipList) &&
        Objects.equals(this.deviceType, shieldCustomerType.deviceType) &&
        Objects.equals(this.shieldType, shieldCustomerType.shieldType) &&
        Objects.equals(this.shieldNum, shieldCustomerType.shieldNum) &&
        Objects.equals(this.identityUser, shieldCustomerType.identityUser) &&
        Objects.equals(this.identitySystem, shieldCustomerType.identitySystem) &&
        Objects.equals(this.addTime, shieldCustomerType.addTime) &&
        Objects.equals(this.modTime, shieldCustomerType.modTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, customId, hitPolicy, ipList, deviceType, shieldType, shieldNum, identityUser, identitySystem, addTime, modTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShieldCustomerType {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    customId: ").append(toIndentedString(customId)).append("\n");
    sb.append("    hitPolicy: ").append(toIndentedString(hitPolicy)).append("\n");
    sb.append("    ipList: ").append(toIndentedString(ipList)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    shieldType: ").append(toIndentedString(shieldType)).append("\n");
    sb.append("    shieldNum: ").append(toIndentedString(shieldNum)).append("\n");
    sb.append("    identityUser: ").append(toIndentedString(identityUser)).append("\n");
    sb.append("    identitySystem: ").append(toIndentedString(identitySystem)).append("\n");
    sb.append("    addTime: ").append(toIndentedString(addTime)).append("\n");
    sb.append("    modTime: ").append(toIndentedString(modTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

