/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.appcenterjob.api;

import com.baidu.dev2.api.sdk.invoke.ApiException;
import com.baidu.dev2.api.sdk.appcenterjob.model.AddBatchPackagesRequestWrapper;
import com.baidu.dev2.api.sdk.appcenterjob.model.AddBatchPackagesResponseWrapper;
import com.baidu.dev2.api.sdk.appcenterjob.model.GetBatchJobDetailsRequestWrapper;
import com.baidu.dev2.api.sdk.appcenterjob.model.GetBatchJobDetailsResponseWrapper;
import com.baidu.dev2.api.sdk.appcenterjob.model.GetBatchJobListResultsRequestWrapper;
import com.baidu.dev2.api.sdk.appcenterjob.model.GetBatchJobListResultsResponseWrapper;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppCenterJobService
 */
@Ignore
public class AppCenterJobServiceTest {

    private final AppCenterJobService api = new AppCenterJobService();

    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addBatchPackagesTest() throws ApiException {
        AddBatchPackagesRequestWrapper addBatchPackagesRequestWrapper = null;
        AddBatchPackagesResponseWrapper response = api.addBatchPackages(addBatchPackagesRequestWrapper);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBatchJobDetailsTest() throws ApiException {
        GetBatchJobDetailsRequestWrapper getBatchJobDetailsRequestWrapper = null;
        GetBatchJobDetailsResponseWrapper response = api.getBatchJobDetails(getBatchJobDetailsRequestWrapper);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBatchJobListResultsTest() throws ApiException {
        GetBatchJobListResultsRequestWrapper getBatchJobListResultsRequestWrapper = null;
        GetBatchJobListResultsResponseWrapper response = api.getBatchJobListResults(getBatchJobListResultsRequestWrapper);

        // TODO: test validations
    }
}
