/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.teslacommonrecord.api;

import com.baidu.dev2.api.sdk.invoke.ApiException;
import com.baidu.dev2.api.sdk.teslacommonrecord.model.GetDictInfoRequestWrapper;
import com.baidu.dev2.api.sdk.teslacommonrecord.model.GetDictInfoResponseWrapper;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeslaCommonRecordService
 */
@Ignore
public class TeslaCommonRecordServiceTest {

    private final TeslaCommonRecordService api = new TeslaCommonRecordService();

    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDictInfoTest() throws ApiException {
        GetDictInfoRequestWrapper getDictInfoRequestWrapper = null;
        GetDictInfoResponseWrapper response = api.getDictInfo(getDictInfoRequestWrapper);

        // TODO: test validations
    }
}
