/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.creative.model;

import java.util.Objects;
import java.util.Arrays;
import com.baidu.dev2.api.sdk.creative.model.ApiOfflineReason;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ApiCreativeType
 */
@JsonPropertyOrder({
  ApiCreativeType.JSON_PROPERTY_CAMPAIGN_ID,
  ApiCreativeType.JSON_PROPERTY_CREATIVE_ID,
  ApiCreativeType.JSON_PROPERTY_ADGROUP_ID,
  ApiCreativeType.JSON_PROPERTY_TITLE,
  ApiCreativeType.JSON_PROPERTY_DESCRIPTION1,
  ApiCreativeType.JSON_PROPERTY_DESCRIPTION2,
  ApiCreativeType.JSON_PROPERTY_PAUSE,
  ApiCreativeType.JSON_PROPERTY_STATUS,
  ApiCreativeType.JSON_PROPERTY_MOBILE_DESTINATION_URL,
  ApiCreativeType.JSON_PROPERTY_MOBILE_DISPLAY_URL,
  ApiCreativeType.JSON_PROPERTY_PC_DESTINATION_URL,
  ApiCreativeType.JSON_PROPERTY_PC_DISPLAY_URL,
  ApiCreativeType.JSON_PROPERTY_OFFLINE_REASONS,
  ApiCreativeType.JSON_PROPERTY_TABS,
  ApiCreativeType.JSON_PROPERTY_DEEPLINK,
  ApiCreativeType.JSON_PROPERTY_MINI_PROGRAM_URL,
  ApiCreativeType.JSON_PROPERTY_CREATE_TIME
})
@JsonTypeName("ApiCreativeType")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ApiCreativeType {
  public static final String JSON_PROPERTY_CAMPAIGN_ID = "campaignId";
  private Long campaignId;

  public static final String JSON_PROPERTY_CREATIVE_ID = "creativeId";
  private Long creativeId;

  public static final String JSON_PROPERTY_ADGROUP_ID = "adgroupId";
  private Long adgroupId;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_DESCRIPTION1 = "description1";
  private String description1;

  public static final String JSON_PROPERTY_DESCRIPTION2 = "description2";
  private String description2;

  public static final String JSON_PROPERTY_PAUSE = "pause";
  private Boolean pause;

  public static final String JSON_PROPERTY_STATUS = "status";
  private Integer status;

  public static final String JSON_PROPERTY_MOBILE_DESTINATION_URL = "mobileDestinationUrl";
  private String mobileDestinationUrl;

  public static final String JSON_PROPERTY_MOBILE_DISPLAY_URL = "mobileDisplayUrl";
  private String mobileDisplayUrl;

  public static final String JSON_PROPERTY_PC_DESTINATION_URL = "pcDestinationUrl";
  private String pcDestinationUrl;

  public static final String JSON_PROPERTY_PC_DISPLAY_URL = "pcDisplayUrl";
  private String pcDisplayUrl;

  public static final String JSON_PROPERTY_OFFLINE_REASONS = "offlineReasons";
  private List<ApiOfflineReason> offlineReasons = null;

  public static final String JSON_PROPERTY_TABS = "tabs";
  private List<Integer> tabs = null;

  public static final String JSON_PROPERTY_DEEPLINK = "deeplink";
  private String deeplink;

  public static final String JSON_PROPERTY_MINI_PROGRAM_URL = "miniProgramUrl";
  private String miniProgramUrl;

  public static final String JSON_PROPERTY_CREATE_TIME = "createTime";
  private String createTime;

  public ApiCreativeType() { 
  }

  public ApiCreativeType campaignId(Long campaignId) {
    
    this.campaignId = campaignId;
    return this;
  }

   /**
   * Get campaignId
   * @return campaignId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CAMPAIGN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCampaignId() {
    return campaignId;
  }


  @JsonProperty(JSON_PROPERTY_CAMPAIGN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampaignId(Long campaignId) {
    this.campaignId = campaignId;
  }


  public ApiCreativeType creativeId(Long creativeId) {
    
    this.creativeId = creativeId;
    return this;
  }

   /**
   * Get creativeId
   * @return creativeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATIVE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreativeId() {
    return creativeId;
  }


  @JsonProperty(JSON_PROPERTY_CREATIVE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreativeId(Long creativeId) {
    this.creativeId = creativeId;
  }


  public ApiCreativeType adgroupId(Long adgroupId) {
    
    this.adgroupId = adgroupId;
    return this;
  }

   /**
   * Get adgroupId
   * @return adgroupId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADGROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAdgroupId() {
    return adgroupId;
  }


  @JsonProperty(JSON_PROPERTY_ADGROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdgroupId(Long adgroupId) {
    this.adgroupId = adgroupId;
  }


  public ApiCreativeType title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(String title) {
    this.title = title;
  }


  public ApiCreativeType description1(String description1) {
    
    this.description1 = description1;
    return this;
  }

   /**
   * Get description1
   * @return description1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription1() {
    return description1;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription1(String description1) {
    this.description1 = description1;
  }


  public ApiCreativeType description2(String description2) {
    
    this.description2 = description2;
    return this;
  }

   /**
   * Get description2
   * @return description2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription2() {
    return description2;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription2(String description2) {
    this.description2 = description2;
  }


  public ApiCreativeType pause(Boolean pause) {
    
    this.pause = pause;
    return this;
  }

   /**
   * Get pause
   * @return pause
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAUSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPause() {
    return pause;
  }


  @JsonProperty(JSON_PROPERTY_PAUSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPause(Boolean pause) {
    this.pause = pause;
  }


  public ApiCreativeType status(Integer status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(Integer status) {
    this.status = status;
  }


  public ApiCreativeType mobileDestinationUrl(String mobileDestinationUrl) {
    
    this.mobileDestinationUrl = mobileDestinationUrl;
    return this;
  }

   /**
   * Get mobileDestinationUrl
   * @return mobileDestinationUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MOBILE_DESTINATION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMobileDestinationUrl() {
    return mobileDestinationUrl;
  }


  @JsonProperty(JSON_PROPERTY_MOBILE_DESTINATION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMobileDestinationUrl(String mobileDestinationUrl) {
    this.mobileDestinationUrl = mobileDestinationUrl;
  }


  public ApiCreativeType mobileDisplayUrl(String mobileDisplayUrl) {
    
    this.mobileDisplayUrl = mobileDisplayUrl;
    return this;
  }

   /**
   * Get mobileDisplayUrl
   * @return mobileDisplayUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MOBILE_DISPLAY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMobileDisplayUrl() {
    return mobileDisplayUrl;
  }


  @JsonProperty(JSON_PROPERTY_MOBILE_DISPLAY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMobileDisplayUrl(String mobileDisplayUrl) {
    this.mobileDisplayUrl = mobileDisplayUrl;
  }


  public ApiCreativeType pcDestinationUrl(String pcDestinationUrl) {
    
    this.pcDestinationUrl = pcDestinationUrl;
    return this;
  }

   /**
   * Get pcDestinationUrl
   * @return pcDestinationUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PC_DESTINATION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPcDestinationUrl() {
    return pcDestinationUrl;
  }


  @JsonProperty(JSON_PROPERTY_PC_DESTINATION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPcDestinationUrl(String pcDestinationUrl) {
    this.pcDestinationUrl = pcDestinationUrl;
  }


  public ApiCreativeType pcDisplayUrl(String pcDisplayUrl) {
    
    this.pcDisplayUrl = pcDisplayUrl;
    return this;
  }

   /**
   * Get pcDisplayUrl
   * @return pcDisplayUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PC_DISPLAY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPcDisplayUrl() {
    return pcDisplayUrl;
  }


  @JsonProperty(JSON_PROPERTY_PC_DISPLAY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPcDisplayUrl(String pcDisplayUrl) {
    this.pcDisplayUrl = pcDisplayUrl;
  }


  public ApiCreativeType offlineReasons(List<ApiOfflineReason> offlineReasons) {
    
    this.offlineReasons = offlineReasons;
    return this;
  }

  public ApiCreativeType addOfflineReasonsItem(ApiOfflineReason offlineReasonsItem) {
    if (this.offlineReasons == null) {
      this.offlineReasons = new ArrayList<>();
    }
    this.offlineReasons.add(offlineReasonsItem);
    return this;
  }

   /**
   * Get offlineReasons
   * @return offlineReasons
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OFFLINE_REASONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ApiOfflineReason> getOfflineReasons() {
    return offlineReasons;
  }


  @JsonProperty(JSON_PROPERTY_OFFLINE_REASONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOfflineReasons(List<ApiOfflineReason> offlineReasons) {
    this.offlineReasons = offlineReasons;
  }


  public ApiCreativeType tabs(List<Integer> tabs) {
    
    this.tabs = tabs;
    return this;
  }

  public ApiCreativeType addTabsItem(Integer tabsItem) {
    if (this.tabs == null) {
      this.tabs = new ArrayList<>();
    }
    this.tabs.add(tabsItem);
    return this;
  }

   /**
   * Get tabs
   * @return tabs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TABS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getTabs() {
    return tabs;
  }


  @JsonProperty(JSON_PROPERTY_TABS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTabs(List<Integer> tabs) {
    this.tabs = tabs;
  }


  public ApiCreativeType deeplink(String deeplink) {
    
    this.deeplink = deeplink;
    return this;
  }

   /**
   * Get deeplink
   * @return deeplink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DEEPLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeeplink() {
    return deeplink;
  }


  @JsonProperty(JSON_PROPERTY_DEEPLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeeplink(String deeplink) {
    this.deeplink = deeplink;
  }


  public ApiCreativeType miniProgramUrl(String miniProgramUrl) {
    
    this.miniProgramUrl = miniProgramUrl;
    return this;
  }

   /**
   * Get miniProgramUrl
   * @return miniProgramUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MINI_PROGRAM_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMiniProgramUrl() {
    return miniProgramUrl;
  }


  @JsonProperty(JSON_PROPERTY_MINI_PROGRAM_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMiniProgramUrl(String miniProgramUrl) {
    this.miniProgramUrl = miniProgramUrl;
  }


  public ApiCreativeType createTime(String createTime) {
    
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreateTime() {
    return createTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiCreativeType apiCreativeType = (ApiCreativeType) o;
    return Objects.equals(this.campaignId, apiCreativeType.campaignId) &&
        Objects.equals(this.creativeId, apiCreativeType.creativeId) &&
        Objects.equals(this.adgroupId, apiCreativeType.adgroupId) &&
        Objects.equals(this.title, apiCreativeType.title) &&
        Objects.equals(this.description1, apiCreativeType.description1) &&
        Objects.equals(this.description2, apiCreativeType.description2) &&
        Objects.equals(this.pause, apiCreativeType.pause) &&
        Objects.equals(this.status, apiCreativeType.status) &&
        Objects.equals(this.mobileDestinationUrl, apiCreativeType.mobileDestinationUrl) &&
        Objects.equals(this.mobileDisplayUrl, apiCreativeType.mobileDisplayUrl) &&
        Objects.equals(this.pcDestinationUrl, apiCreativeType.pcDestinationUrl) &&
        Objects.equals(this.pcDisplayUrl, apiCreativeType.pcDisplayUrl) &&
        Objects.equals(this.offlineReasons, apiCreativeType.offlineReasons) &&
        Objects.equals(this.tabs, apiCreativeType.tabs) &&
        Objects.equals(this.deeplink, apiCreativeType.deeplink) &&
        Objects.equals(this.miniProgramUrl, apiCreativeType.miniProgramUrl) &&
        Objects.equals(this.createTime, apiCreativeType.createTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignId, creativeId, adgroupId, title, description1, description2, pause, status, mobileDestinationUrl, mobileDisplayUrl, pcDestinationUrl, pcDisplayUrl, offlineReasons, tabs, deeplink, miniProgramUrl, createTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiCreativeType {\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    creativeId: ").append(toIndentedString(creativeId)).append("\n");
    sb.append("    adgroupId: ").append(toIndentedString(adgroupId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description1: ").append(toIndentedString(description1)).append("\n");
    sb.append("    description2: ").append(toIndentedString(description2)).append("\n");
    sb.append("    pause: ").append(toIndentedString(pause)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    mobileDestinationUrl: ").append(toIndentedString(mobileDestinationUrl)).append("\n");
    sb.append("    mobileDisplayUrl: ").append(toIndentedString(mobileDisplayUrl)).append("\n");
    sb.append("    pcDestinationUrl: ").append(toIndentedString(pcDestinationUrl)).append("\n");
    sb.append("    pcDisplayUrl: ").append(toIndentedString(pcDisplayUrl)).append("\n");
    sb.append("    offlineReasons: ").append(toIndentedString(offlineReasons)).append("\n");
    sb.append("    tabs: ").append(toIndentedString(tabs)).append("\n");
    sb.append("    deeplink: ").append(toIndentedString(deeplink)).append("\n");
    sb.append("    miniProgramUrl: ").append(toIndentedString(miniProgramUrl)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

