/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.creative.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreativeTemplateRequest
 */
@JsonPropertyOrder({
  CreativeTemplateRequest.JSON_PROPERTY_CREATIVE_NAME,
  CreativeTemplateRequest.JSON_PROPERTY_LIMIT,
  CreativeTemplateRequest.JSON_PROPERTY_DESC,
  CreativeTemplateRequest.JSON_PROPERTY_ORDER_BY,
  CreativeTemplateRequest.JSON_PROPERTY_ITEM
})
@JsonTypeName("CreativeTemplateRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreativeTemplateRequest {
  public static final String JSON_PROPERTY_CREATIVE_NAME = "creativeName";
  private String creativeName;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  private List<Integer> limit = null;

  public static final String JSON_PROPERTY_DESC = "desc";
  private Boolean desc;

  public static final String JSON_PROPERTY_ORDER_BY = "orderBy";
  private String orderBy;

  public static final String JSON_PROPERTY_ITEM = "item";
  private Object item;

  public CreativeTemplateRequest() { 
  }

  public CreativeTemplateRequest creativeName(String creativeName) {
    
    this.creativeName = creativeName;
    return this;
  }

   /**
   * Get creativeName
   * @return creativeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATIVE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreativeName() {
    return creativeName;
  }


  @JsonProperty(JSON_PROPERTY_CREATIVE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreativeName(String creativeName) {
    this.creativeName = creativeName;
  }


  public CreativeTemplateRequest limit(List<Integer> limit) {
    
    this.limit = limit;
    return this;
  }

  public CreativeTemplateRequest addLimitItem(Integer limitItem) {
    if (this.limit == null) {
      this.limit = new ArrayList<>();
    }
    this.limit.add(limitItem);
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getLimit() {
    return limit;
  }


  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimit(List<Integer> limit) {
    this.limit = limit;
  }


  public CreativeTemplateRequest desc(Boolean desc) {
    
    this.desc = desc;
    return this;
  }

   /**
   * Get desc
   * @return desc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDesc() {
    return desc;
  }


  @JsonProperty(JSON_PROPERTY_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDesc(Boolean desc) {
    this.desc = desc;
  }


  public CreativeTemplateRequest orderBy(String orderBy) {
    
    this.orderBy = orderBy;
    return this;
  }

   /**
   * Get orderBy
   * @return orderBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORDER_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderBy() {
    return orderBy;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderBy(String orderBy) {
    this.orderBy = orderBy;
  }


  public CreativeTemplateRequest item(Object item) {
    
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getItem() {
    return item;
  }


  @JsonProperty(JSON_PROPERTY_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItem(Object item) {
    this.item = item;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreativeTemplateRequest creativeTemplateRequest = (CreativeTemplateRequest) o;
    return Objects.equals(this.creativeName, creativeTemplateRequest.creativeName) &&
        Objects.equals(this.limit, creativeTemplateRequest.limit) &&
        Objects.equals(this.desc, creativeTemplateRequest.desc) &&
        Objects.equals(this.orderBy, creativeTemplateRequest.orderBy) &&
        Objects.equals(this.item, creativeTemplateRequest.item);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creativeName, limit, desc, orderBy, item);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreativeTemplateRequest {\n");
    sb.append("    creativeName: ").append(toIndentedString(creativeName)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    orderBy: ").append(toIndentedString(orderBy)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

