/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.subshopopenapi.model;

import com.baidu.dev2.api.sdk.subshopopenapi.model.ShopQualifyVo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlatCompanyVo
 */
public class PlatCompanyVoTest {
    private final PlatCompanyVo model = new PlatCompanyVo();

    /**
     * Model tests for PlatCompanyVo
     */
    @Test
    public void testPlatCompanyVo() {
        // TODO: test PlatCompanyVo
    }

    /**
     * Test the property 'licenseUrl'
     */
    @Test
    public void licenseUrlTest() {
        // TODO: test licenseUrl
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'businessLicense'
     */
    @Test
    public void businessLicenseTest() {
        // TODO: test businessLicense
    }

    /**
     * Test the property 'supplierType'
     */
    @Test
    public void supplierTypeTest() {
        // TODO: test supplierType
    }

    /**
     * Test the property 'industryId'
     */
    @Test
    public void industryIdTest() {
        // TODO: test industryId
    }

    /**
     * Test the property 'industryQualifyVo'
     */
    @Test
    public void industryQualifyVoTest() {
        // TODO: test industryQualifyVo
    }

    /**
     * Test the property 'licenseStartTime'
     */
    @Test
    public void licenseStartTimeTest() {
        // TODO: test licenseStartTime
    }

    /**
     * Test the property 'licenseEndTime'
     */
    @Test
    public void licenseEndTimeTest() {
        // TODO: test licenseEndTime
    }

    /**
     * Test the property 'authCapital'
     */
    @Test
    public void authCapitalTest() {
        // TODO: test authCapital
    }

    /**
     * Test the property 'businessProvince'
     */
    @Test
    public void businessProvinceTest() {
        // TODO: test businessProvince
    }

    /**
     * Test the property 'businessCity'
     */
    @Test
    public void businessCityTest() {
        // TODO: test businessCity
    }

    /**
     * Test the property 'businessDetailAddress'
     */
    @Test
    public void businessDetailAddressTest() {
        // TODO: test businessDetailAddress
    }

    /**
     * Test the property 'businessScope'
     */
    @Test
    public void businessScopeTest() {
        // TODO: test businessScope
    }

    /**
     * Test the property 'accountQualifySame'
     */
    @Test
    public void accountQualifySameTest() {
        // TODO: test accountQualifySame
    }

    /**
     * Test the property 'guaranteeLetterUrl'
     */
    @Test
    public void guaranteeLetterUrlTest() {
        // TODO: test guaranteeLetterUrl
    }

    /**
     * Test the property 'subShopType'
     */
    @Test
    public void subShopTypeTest() {
        // TODO: test subShopType
    }

    /**
     * Test the property 'businessArea'
     */
    @Test
    public void businessAreaTest() {
        // TODO: test businessArea
    }

}
