/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.campaignshopping.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Text
 */
public class TextTest {
    private final Text model = new Text();

    /**
     * Model tests for Text
     */
    @Test
    public void testText() {
        // TODO: test Text
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'astat'
     */
    @Test
    public void astatTest() {
        // TODO: test astat
    }

    /**
     * Test the property 'refuseReason'
     */
    @Test
    public void refuseReasonTest() {
        // TODO: test refuseReason
    }

    /**
     * Test the property 'elementId'
     */
    @Test
    public void elementIdTest() {
        // TODO: test elementId
    }

}
