/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.appcenterjob.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BatchJobResultDetailDto
 */
@JsonPropertyOrder({
  BatchJobResultDetailDto.JSON_PROPERTY_TOTAL_COUNT,
  BatchJobResultDetailDto.JSON_PROPERTY_SUCCESS_COUNT,
  BatchJobResultDetailDto.JSON_PROPERTY_FAIL_COUNT,
  BatchJobResultDetailDto.JSON_PROPERTY_WORKING_COUNT
})
@JsonTypeName("BatchJobResultDetailDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BatchJobResultDetailDto {
  public static final String JSON_PROPERTY_TOTAL_COUNT = "totalCount";
  private Integer totalCount;

  public static final String JSON_PROPERTY_SUCCESS_COUNT = "successCount";
  private Integer successCount;

  public static final String JSON_PROPERTY_FAIL_COUNT = "failCount";
  private Integer failCount;

  public static final String JSON_PROPERTY_WORKING_COUNT = "workingCount";
  private Integer workingCount;

  public BatchJobResultDetailDto() { 
  }

  public BatchJobResultDetailDto totalCount(Integer totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalCount() {
    return totalCount;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  public BatchJobResultDetailDto successCount(Integer successCount) {
    
    this.successCount = successCount;
    return this;
  }

   /**
   * Get successCount
   * @return successCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUCCESS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSuccessCount() {
    return successCount;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccessCount(Integer successCount) {
    this.successCount = successCount;
  }


  public BatchJobResultDetailDto failCount(Integer failCount) {
    
    this.failCount = failCount;
    return this;
  }

   /**
   * Get failCount
   * @return failCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FAIL_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFailCount() {
    return failCount;
  }


  @JsonProperty(JSON_PROPERTY_FAIL_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailCount(Integer failCount) {
    this.failCount = failCount;
  }


  public BatchJobResultDetailDto workingCount(Integer workingCount) {
    
    this.workingCount = workingCount;
    return this;
  }

   /**
   * Get workingCount
   * @return workingCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORKING_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWorkingCount() {
    return workingCount;
  }


  @JsonProperty(JSON_PROPERTY_WORKING_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkingCount(Integer workingCount) {
    this.workingCount = workingCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchJobResultDetailDto batchJobResultDetailDto = (BatchJobResultDetailDto) o;
    return Objects.equals(this.totalCount, batchJobResultDetailDto.totalCount) &&
        Objects.equals(this.successCount, batchJobResultDetailDto.successCount) &&
        Objects.equals(this.failCount, batchJobResultDetailDto.failCount) &&
        Objects.equals(this.workingCount, batchJobResultDetailDto.workingCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCount, successCount, failCount, workingCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchJobResultDetailDto {\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    successCount: ").append(toIndentedString(successCount)).append("\n");
    sb.append("    failCount: ").append(toIndentedString(failCount)).append("\n");
    sb.append("    workingCount: ").append(toIndentedString(workingCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

