/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.platproduct.model;

import java.util.Objects;
import java.util.Arrays;
import com.baidu.dev2.api.sdk.platproduct.model.PlatProductSkuSpecVo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProductSkusVo
 */
@JsonPropertyOrder({
  ProductSkusVo.JSON_PROPERTY_SKU_ID,
  ProductSkusVo.JSON_PROPERTY_PRICE,
  ProductSkusVo.JSON_PROPERTY_SALE_PRICE,
  ProductSkusVo.JSON_PROPERTY_STOCK,
  ProductSkusVo.JSON_PROPERTY_LOCKED_STOCK,
  ProductSkusVo.JSON_PROPERTY_REST_STOCK,
  ProductSkusVo.JSON_PROPERTY_SALES,
  ProductSkusVo.JSON_PROPERTY_PIC_URL,
  ProductSkusVo.JSON_PROPERTY_ALARM_STOCK,
  ProductSkusVo.JSON_PROPERTY_WEIGHT,
  ProductSkusVo.JSON_PROPERTY_SPECIFICATIONS
})
@JsonTypeName("ProductSkusVo")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ProductSkusVo {
  public static final String JSON_PROPERTY_SKU_ID = "skuId";
  private Long skuId;

  public static final String JSON_PROPERTY_PRICE = "price";
  private java.math.BigDecimal price;

  public static final String JSON_PROPERTY_SALE_PRICE = "salePrice";
  private java.math.BigDecimal salePrice;

  public static final String JSON_PROPERTY_STOCK = "stock";
  private Long stock;

  public static final String JSON_PROPERTY_LOCKED_STOCK = "lockedStock";
  private Long lockedStock;

  public static final String JSON_PROPERTY_REST_STOCK = "restStock";
  private Long restStock;

  public static final String JSON_PROPERTY_SALES = "sales";
  private Long sales;

  public static final String JSON_PROPERTY_PIC_URL = "picUrl";
  private String picUrl;

  public static final String JSON_PROPERTY_ALARM_STOCK = "alarmStock";
  private Long alarmStock;

  public static final String JSON_PROPERTY_WEIGHT = "weight";
  private java.math.BigDecimal weight;

  public static final String JSON_PROPERTY_SPECIFICATIONS = "specifications";
  private List<PlatProductSkuSpecVo> specifications = null;

  public ProductSkusVo() { 
  }

  public ProductSkusVo skuId(Long skuId) {
    
    this.skuId = skuId;
    return this;
  }

   /**
   * Get skuId
   * @return skuId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SKU_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSkuId() {
    return skuId;
  }


  @JsonProperty(JSON_PROPERTY_SKU_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSkuId(Long skuId) {
    this.skuId = skuId;
  }


  public ProductSkusVo price(java.math.BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.math.BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(java.math.BigDecimal price) {
    this.price = price;
  }


  public ProductSkusVo salePrice(java.math.BigDecimal salePrice) {
    
    this.salePrice = salePrice;
    return this;
  }

   /**
   * Get salePrice
   * @return salePrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SALE_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.math.BigDecimal getSalePrice() {
    return salePrice;
  }


  @JsonProperty(JSON_PROPERTY_SALE_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSalePrice(java.math.BigDecimal salePrice) {
    this.salePrice = salePrice;
  }


  public ProductSkusVo stock(Long stock) {
    
    this.stock = stock;
    return this;
  }

   /**
   * Get stock
   * @return stock
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStock() {
    return stock;
  }


  @JsonProperty(JSON_PROPERTY_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStock(Long stock) {
    this.stock = stock;
  }


  public ProductSkusVo lockedStock(Long lockedStock) {
    
    this.lockedStock = lockedStock;
    return this;
  }

   /**
   * Get lockedStock
   * @return lockedStock
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCKED_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLockedStock() {
    return lockedStock;
  }


  @JsonProperty(JSON_PROPERTY_LOCKED_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockedStock(Long lockedStock) {
    this.lockedStock = lockedStock;
  }


  public ProductSkusVo restStock(Long restStock) {
    
    this.restStock = restStock;
    return this;
  }

   /**
   * Get restStock
   * @return restStock
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REST_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRestStock() {
    return restStock;
  }


  @JsonProperty(JSON_PROPERTY_REST_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestStock(Long restStock) {
    this.restStock = restStock;
  }


  public ProductSkusVo sales(Long sales) {
    
    this.sales = sales;
    return this;
  }

   /**
   * Get sales
   * @return sales
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SALES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSales() {
    return sales;
  }


  @JsonProperty(JSON_PROPERTY_SALES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSales(Long sales) {
    this.sales = sales;
  }


  public ProductSkusVo picUrl(String picUrl) {
    
    this.picUrl = picUrl;
    return this;
  }

   /**
   * Get picUrl
   * @return picUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PIC_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPicUrl() {
    return picUrl;
  }


  @JsonProperty(JSON_PROPERTY_PIC_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPicUrl(String picUrl) {
    this.picUrl = picUrl;
  }


  public ProductSkusVo alarmStock(Long alarmStock) {
    
    this.alarmStock = alarmStock;
    return this;
  }

   /**
   * Get alarmStock
   * @return alarmStock
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALARM_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAlarmStock() {
    return alarmStock;
  }


  @JsonProperty(JSON_PROPERTY_ALARM_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlarmStock(Long alarmStock) {
    this.alarmStock = alarmStock;
  }


  public ProductSkusVo weight(java.math.BigDecimal weight) {
    
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.math.BigDecimal getWeight() {
    return weight;
  }


  @JsonProperty(JSON_PROPERTY_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeight(java.math.BigDecimal weight) {
    this.weight = weight;
  }


  public ProductSkusVo specifications(List<PlatProductSkuSpecVo> specifications) {
    
    this.specifications = specifications;
    return this;
  }

  public ProductSkusVo addSpecificationsItem(PlatProductSkuSpecVo specificationsItem) {
    if (this.specifications == null) {
      this.specifications = new ArrayList<>();
    }
    this.specifications.add(specificationsItem);
    return this;
  }

   /**
   * Get specifications
   * @return specifications
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SPECIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PlatProductSkuSpecVo> getSpecifications() {
    return specifications;
  }


  @JsonProperty(JSON_PROPERTY_SPECIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpecifications(List<PlatProductSkuSpecVo> specifications) {
    this.specifications = specifications;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductSkusVo productSkusVo = (ProductSkusVo) o;
    return Objects.equals(this.skuId, productSkusVo.skuId) &&
        Objects.equals(this.price, productSkusVo.price) &&
        Objects.equals(this.salePrice, productSkusVo.salePrice) &&
        Objects.equals(this.stock, productSkusVo.stock) &&
        Objects.equals(this.lockedStock, productSkusVo.lockedStock) &&
        Objects.equals(this.restStock, productSkusVo.restStock) &&
        Objects.equals(this.sales, productSkusVo.sales) &&
        Objects.equals(this.picUrl, productSkusVo.picUrl) &&
        Objects.equals(this.alarmStock, productSkusVo.alarmStock) &&
        Objects.equals(this.weight, productSkusVo.weight) &&
        Objects.equals(this.specifications, productSkusVo.specifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(skuId, price, salePrice, stock, lockedStock, restStock, sales, picUrl, alarmStock, weight, specifications);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductSkusVo {\n");
    sb.append("    skuId: ").append(toIndentedString(skuId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    salePrice: ").append(toIndentedString(salePrice)).append("\n");
    sb.append("    stock: ").append(toIndentedString(stock)).append("\n");
    sb.append("    lockedStock: ").append(toIndentedString(lockedStock)).append("\n");
    sb.append("    restStock: ").append(toIndentedString(restStock)).append("\n");
    sb.append("    sales: ").append(toIndentedString(sales)).append("\n");
    sb.append("    picUrl: ").append(toIndentedString(picUrl)).append("\n");
    sb.append("    alarmStock: ").append(toIndentedString(alarmStock)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    specifications: ").append(toIndentedString(specifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

