/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.dpaapiproductset.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProductSetStatusResponse
 */
@JsonPropertyOrder({
  ProductSetStatusResponse.JSON_PROPERTY_OPERATED_STATUS,
  ProductSetStatusResponse.JSON_PROPERTY_FAILED_PRODUCT_SET_IDS
})
@JsonTypeName("ProductSetStatusResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ProductSetStatusResponse {
  public static final String JSON_PROPERTY_OPERATED_STATUS = "operatedStatus";
  private String operatedStatus;

  public static final String JSON_PROPERTY_FAILED_PRODUCT_SET_IDS = "failedProductSetIds";
  private List<Long> failedProductSetIds = null;

  public ProductSetStatusResponse() { 
  }

  public ProductSetStatusResponse operatedStatus(String operatedStatus) {
    
    this.operatedStatus = operatedStatus;
    return this;
  }

   /**
   * Get operatedStatus
   * @return operatedStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OPERATED_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperatedStatus() {
    return operatedStatus;
  }


  @JsonProperty(JSON_PROPERTY_OPERATED_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperatedStatus(String operatedStatus) {
    this.operatedStatus = operatedStatus;
  }


  public ProductSetStatusResponse failedProductSetIds(List<Long> failedProductSetIds) {
    
    this.failedProductSetIds = failedProductSetIds;
    return this;
  }

  public ProductSetStatusResponse addFailedProductSetIdsItem(Long failedProductSetIdsItem) {
    if (this.failedProductSetIds == null) {
      this.failedProductSetIds = new ArrayList<>();
    }
    this.failedProductSetIds.add(failedProductSetIdsItem);
    return this;
  }

   /**
   * Get failedProductSetIds
   * @return failedProductSetIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FAILED_PRODUCT_SET_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getFailedProductSetIds() {
    return failedProductSetIds;
  }


  @JsonProperty(JSON_PROPERTY_FAILED_PRODUCT_SET_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailedProductSetIds(List<Long> failedProductSetIds) {
    this.failedProductSetIds = failedProductSetIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductSetStatusResponse productSetStatusResponse = (ProductSetStatusResponse) o;
    return Objects.equals(this.operatedStatus, productSetStatusResponse.operatedStatus) &&
        Objects.equals(this.failedProductSetIds, productSetStatusResponse.failedProductSetIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operatedStatus, failedProductSetIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductSetStatusResponse {\n");
    sb.append("    operatedStatus: ").append(toIndentedString(operatedStatus)).append("\n");
    sb.append("    failedProductSetIds: ").append(toIndentedString(failedProductSetIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

