/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.page.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BroadCastQueryRequest
 */
public class BroadCastQueryRequestTest {
    private final BroadCastQueryRequest model = new BroadCastQueryRequest();

    /**
     * Model tests for BroadCastQueryRequest
     */
    @Test
    public void testBroadCastQueryRequest() {
        // TODO: test BroadCastQueryRequest
    }

    /**
     * Test the property 'liveRoomTitle'
     */
    @Test
    public void liveRoomTitleTest() {
        // TODO: test liveRoomTitle
    }

    /**
     * Test the property 'anchorName'
     */
    @Test
    public void anchorNameTest() {
        // TODO: test anchorName
    }

    /**
     * Test the property 'liveUrl'
     */
    @Test
    public void liveUrlTest() {
        // TODO: test liveUrl
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
