"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.adgroupfeed.model.update_adgroup_feed_request_wrapper_body import UpdateAdgroupFeedRequestWrapperBody
from baiduads.common.model.api_request_header import ApiRequestHeader
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['UpdateAdgroupFeedRequestWrapperBody'] = UpdateAdgroupFeedRequestWrapperBody
from baiduads.adgroupfeed.model.update_adgroup_feed_request_wrapper import UpdateAdgroupFeedRequestWrapper


class TestUpdateAdgroupFeedRequestWrapper(unittest.TestCase):
    """UpdateAdgroupFeedRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateAdgroupFeedRequestWrapper(self):
        """Test UpdateAdgroupFeedRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateAdgroupFeedRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
