"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.fmdatareport.model.phone_recordings_vo import PhoneRecordingsVo


class TestPhoneRecordingsVo(unittest.TestCase):
    """PhoneRecordingsVo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPhoneRecordingsVo(self):
        """Test PhoneRecordingsVo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PhoneRecordingsVo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
