"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.traceapi.model.update_trans_trace_response_wrapper_body import UpdateTransTraceResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['UpdateTransTraceResponseWrapperBody'] = UpdateTransTraceResponseWrapperBody
from baiduads.traceapi.model.update_trans_trace_response_wrapper import UpdateTransTraceResponseWrapper


class TestUpdateTransTraceResponseWrapper(unittest.TestCase):
    """UpdateTransTraceResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateTransTraceResponseWrapper(self):
        """Test UpdateTransTraceResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateTransTraceResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
