"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.videoauditapi.model.video_audit_count_response import VideoAuditCountResponse
globals()['VideoAuditCountResponse'] = VideoAuditCountResponse
from baiduads.videoauditapi.model.query_count_response_wrapper_body import QueryCountResponseWrapperBody


class TestQueryCountResponseWrapperBody(unittest.TestCase):
    """QueryCountResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryCountResponseWrapperBody(self):
        """Test QueryCountResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryCountResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
