"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.imagesegment.model.image_segment_type import ImageSegmentType
globals()['ImageSegmentType'] = ImageSegmentType
from baiduads.imagesegment.model.update_image_segment_type import UpdateImageSegmentType


class TestUpdateImageSegmentType(unittest.TestCase):
    """UpdateImageSegmentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateImageSegmentType(self):
        """Test UpdateImageSegmentType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateImageSegmentType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
