"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.cyctemplate.model.cyc_template_response_dto import CycTemplateResponseDto
globals()['CycTemplateResponseDto'] = CycTemplateResponseDto
from baiduads.cyctemplate.model.get_template_response_wrapper_body import GetTemplateResponseWrapperBody


class TestGetTemplateResponseWrapperBody(unittest.TestCase):
    """GetTemplateResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTemplateResponseWrapperBody(self):
        """Test GetTemplateResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTemplateResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
