"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.creativefeed.model.query_recommend_reasons_response_wrapper_body import QueryRecommendReasonsResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['QueryRecommendReasonsResponseWrapperBody'] = QueryRecommendReasonsResponseWrapperBody
from baiduads.creativefeed.model.bind_recommend_reasons_response_wrapper import BindRecommendReasonsResponseWrapper


class TestBindRecommendReasonsResponseWrapper(unittest.TestCase):
    """BindRecommendReasonsResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBindRecommendReasonsResponseWrapper(self):
        """Test BindRecommendReasonsResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BindRecommendReasonsResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
