"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import unittest

import baiduads
from adgroup.api.adgroup_service import AdgroupService  # noqa: E501


class TestAdgroupService(unittest.TestCase):
    """AdgroupService unit test stubs"""

    def setUp(self):
        self.api = AdgroupService()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_adgroup(self):
        """Test case for add_adgroup

        """
        pass

    def test_delete_adgroup(self):
        """Test case for delete_adgroup

        """
        pass

    def test_get_adgroup(self):
        """Test case for get_adgroup

        """
        pass

    def test_update_adgroup(self):
        """Test case for update_adgroup

        """
        pass


if __name__ == '__main__':
    unittest.main()
