"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.negativeword.model.schedule_price_factor import SchedulePriceFactor


class TestSchedulePriceFactor(unittest.TestCase):
    """SchedulePriceFactor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchedulePriceFactor(self):
        """Test SchedulePriceFactor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SchedulePriceFactor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
