"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.materialarticle.model.article_image_dto import ArticleImageDto
globals()['ArticleImageDto'] = ArticleImageDto
from baiduads.materialarticle.model.article_image import ArticleImage


class TestArticleImage(unittest.TestCase):
    """ArticleImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArticleImage(self):
        """Test ArticleImage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ArticleImage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
