"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.accountfeed.model.account_feed_type import AccountFeedType
globals()['AccountFeedType'] = AccountFeedType
from baiduads.accountfeed.model.update_account_feed_request_wrapper_body import UpdateAccountFeedRequestWrapperBody


class TestUpdateAccountFeedRequestWrapperBody(unittest.TestCase):
    """UpdateAccountFeedRequestWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateAccountFeedRequestWrapperBody(self):
        """Test UpdateAccountFeedRequestWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateAccountFeedRequestWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
