"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.appcenterpackage.model.tree_node import TreeNode


class TestTreeNode(unittest.TestCase):
    """TreeNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTreeNode(self):
        """Test TreeNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TreeNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
