"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.adgroupimagesegmentbind.model.adgroup_image_segment_bind_type import AdgroupImageSegmentBindType


class TestAdgroupImageSegmentBindType(unittest.TestCase):
    """AdgroupImageSegmentBindType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdgroupImageSegmentBindType(self):
        """Test AdgroupImageSegmentBindType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AdgroupImageSegmentBindType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
