"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.searchfeed.model.auto_bid_ocpc import AutoBidOcpc
globals()['AutoBidOcpc'] = AutoBidOcpc
from baiduads.searchfeed.model.auto_bid_cost_request import AutoBidCostRequest


class TestAutoBidCostRequest(unittest.TestCase):
    """AutoBidCostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutoBidCostRequest(self):
        """Test AutoBidCostRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AutoBidCostRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
