"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.creativefeed.model.get_creative_feed_preview_url_with_preview_source_response_wrapper_body import GetCreativeFeedPreviewUrlWithPreviewSourceResponseWrapperBody


class TestGetCreativeFeedPreviewUrlWithPreviewSourceResponseWrapperBody(unittest.TestCase):
    """GetCreativeFeedPreviewUrlWithPreviewSourceResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCreativeFeedPreviewUrlWithPreviewSourceResponseWrapperBody(self):
        """Test GetCreativeFeedPreviewUrlWithPreviewSourceResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCreativeFeedPreviewUrlWithPreviewSourceResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
