"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.share.model.share_save_request import ShareSaveRequest


class TestShareSaveRequest(unittest.TestCase):
    """ShareSaveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShareSaveRequest(self):
        """Test ShareSaveRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ShareSaveRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
