"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.dpacreative.model.update_creative_group_response_wrapper_body import UpdateCreativeGroupResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['UpdateCreativeGroupResponseWrapperBody'] = UpdateCreativeGroupResponseWrapperBody
from baiduads.dpacreative.model.update_creative_group_response_wrapper import UpdateCreativeGroupResponseWrapper


class TestUpdateCreativeGroupResponseWrapper(unittest.TestCase):
    """UpdateCreativeGroupResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateCreativeGroupResponseWrapper(self):
        """Test UpdateCreativeGroupResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateCreativeGroupResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
