"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.negativeword.model.price_strategy_type import PriceStrategyType
globals()['PriceStrategyType'] = PriceStrategyType
from baiduads.negativeword.model.price_strategy_info import PriceStrategyInfo


class TestPriceStrategyInfo(unittest.TestCase):
    """PriceStrategyInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriceStrategyInfo(self):
        """Test PriceStrategyInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PriceStrategyInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
