"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.rtafeed.model.rta_setting_type import RtaSettingType
globals()['RtaSettingType'] = RtaSettingType
from baiduads.rtafeed.model.update_rta_setting_response_wrapper_body import UpdateRtaSettingResponseWrapperBody


class TestUpdateRtaSettingResponseWrapperBody(unittest.TestCase):
    """UpdateRtaSettingResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateRtaSettingResponseWrapperBody(self):
        """Test UpdateRtaSettingResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateRtaSettingResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
