"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.accountshopping.model.update_account_shopping_request import UpdateAccountShoppingRequest
from baiduads.common.model.api_request_header import ApiRequestHeader
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['UpdateAccountShoppingRequest'] = UpdateAccountShoppingRequest
from baiduads.accountshopping.model.update_account_shopping_request_wrapper import UpdateAccountShoppingRequestWrapper


class TestUpdateAccountShoppingRequestWrapper(unittest.TestCase):
    """UpdateAccountShoppingRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateAccountShoppingRequestWrapper(self):
        """Test UpdateAccountShoppingRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateAccountShoppingRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
