"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_request_header import ApiRequestHeader
from baiduads.newcreative.model.creative_group_id_request import CreativeGroupIdRequest
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['CreativeGroupIdRequest'] = CreativeGroupIdRequest
from baiduads.newcreative.model.get_creative_group_request_wrapper import GetCreativeGroupRequestWrapper


class TestGetCreativeGroupRequestWrapper(unittest.TestCase):
    """GetCreativeGroupRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCreativeGroupRequestWrapper(self):
        """Test GetCreativeGroupRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCreativeGroupRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
