"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.storefunction.model.decoration_page import DecorationPage
globals()['DecorationPage'] = DecorationPage
from baiduads.storefunction.model.store_info_type import StoreInfoType


class TestStoreInfoType(unittest.TestCase):
    """StoreInfoType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoreInfoType(self):
        """Test StoreInfoType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StoreInfoType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
