"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.negativeword.model.adgroup_type import AdgroupType
from baiduads.negativeword.model.area_price_factor import AreaPriceFactor
from baiduads.negativeword.model.business_label_type import BusinessLabelType
from baiduads.negativeword.model.campaign_cost_manager import CampaignCostManager
from baiduads.negativeword.model.campaign_distance_range_factor import CampaignDistanceRangeFactor
from baiduads.negativeword.model.campaign_external_flow import CampaignExternalFlow
from baiduads.negativeword.model.campaign_hct import CampaignHct
from baiduads.negativeword.model.campaign_region_area import CampaignRegionArea
from baiduads.negativeword.model.campaign_region_store import CampaignRegionStore
from baiduads.negativeword.model.distance_price_factor_type import DistancePriceFactorType
from baiduads.negativeword.model.dynamic_creative_grab_url import DynamicCreativeGrabUrl
from baiduads.negativeword.model.novel_promotion_page_type import NovelPromotionPageType
from baiduads.negativeword.model.offline_reason import OfflineReason
from baiduads.negativeword.model.offline_time_type import OfflineTimeType
from baiduads.negativeword.model.price_strategy_info import PriceStrategyInfo
from baiduads.negativeword.model.region_poi_type import RegionPOIType
from baiduads.negativeword.model.region_price_factor import RegionPriceFactor
from baiduads.negativeword.model.region_target_district_type import RegionTargetDistrictType
from baiduads.negativeword.model.schedule_price_factor import SchedulePriceFactor
from baiduads.negativeword.model.schedule_type import ScheduleType
from baiduads.negativeword.model.share_repertory_type import ShareRepertoryType
from baiduads.negativeword.model.store_page_info_type import StorePageInfoType
globals()['AdgroupType'] = AdgroupType
globals()['AreaPriceFactor'] = AreaPriceFactor
globals()['BusinessLabelType'] = BusinessLabelType
globals()['CampaignCostManager'] = CampaignCostManager
globals()['CampaignDistanceRangeFactor'] = CampaignDistanceRangeFactor
globals()['CampaignExternalFlow'] = CampaignExternalFlow
globals()['CampaignHct'] = CampaignHct
globals()['CampaignRegionArea'] = CampaignRegionArea
globals()['CampaignRegionStore'] = CampaignRegionStore
globals()['DistancePriceFactorType'] = DistancePriceFactorType
globals()['DynamicCreativeGrabUrl'] = DynamicCreativeGrabUrl
globals()['NovelPromotionPageType'] = NovelPromotionPageType
globals()['OfflineReason'] = OfflineReason
globals()['OfflineTimeType'] = OfflineTimeType
globals()['PriceStrategyInfo'] = PriceStrategyInfo
globals()['RegionPOIType'] = RegionPOIType
globals()['RegionPriceFactor'] = RegionPriceFactor
globals()['RegionTargetDistrictType'] = RegionTargetDistrictType
globals()['SchedulePriceFactor'] = SchedulePriceFactor
globals()['ScheduleType'] = ScheduleType
globals()['ShareRepertoryType'] = ShareRepertoryType
globals()['StorePageInfoType'] = StorePageInfoType
from baiduads.negativeword.model.campaign_type import CampaignType


class TestCampaignType(unittest.TestCase):
    """CampaignType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCampaignType(self):
        """Test CampaignType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CampaignType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
