"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.fctranstraceapi.model.add_fc_trans_trace_response_wrapper_body import AddFcTransTraceResponseWrapperBody
globals()['AddFcTransTraceResponseWrapperBody'] = AddFcTransTraceResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
from baiduads.fctranstraceapi.model.add_fc_trans_trace_response_wrapper import AddFcTransTraceResponseWrapper


class TestAddFcTransTraceResponseWrapper(unittest.TestCase):
    """AddFcTransTraceResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddFcTransTraceResponseWrapper(self):
        """Test AddFcTransTraceResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddFcTransTraceResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
