"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_request_header import ApiRequestHeader
from baiduads.industrytraffic.model.search_trend_request import SearchTrendRequest
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['SearchTrendRequest'] = SearchTrendRequest
from baiduads.industrytraffic.model.get_search_trend_by_dev2_request_wrapper import GetSearchTrendByDev2RequestWrapper


class TestGetSearchTrendByDev2RequestWrapper(unittest.TestCase):
    """GetSearchTrendByDev2RequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSearchTrendByDev2RequestWrapper(self):
        """Test GetSearchTrendByDev2RequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSearchTrendByDev2RequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
