"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.platproduct.model.plat_product_get_detail_request import PlatProductGetDetailRequest


class TestPlatProductGetDetailRequest(unittest.TestCase):
    """PlatProductGetDetailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlatProductGetDetailRequest(self):
        """Test PlatProductGetDetailRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlatProductGetDetailRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
