"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.pvsearchfunction.model.pv_search_response import PvSearchResponse
globals()['PvSearchResponse'] = PvSearchResponse
from baiduads.pvsearchfunction.model.get_pv_search_response_wrapper_body import GetPvSearchResponseWrapperBody


class TestGetPvSearchResponseWrapperBody(unittest.TestCase):
    """GetPvSearchResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPvSearchResponseWrapperBody(self):
        """Test GetPvSearchResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPvSearchResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
