"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.advice.model.ngt_word_type import NgtWordType


class TestNgtWordType(unittest.TestCase):
    """NgtWordType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNgtWordType(self):
        """Test NgtWordType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NgtWordType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
