"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import unittest

import baiduads
from videofeed.api.video_feed_service import VideoFeedService  # noqa: E501


class TestVideoFeedService(unittest.TestCase):
    """VideoFeedService unit test stubs"""

    def setUp(self):
        self.api = VideoFeedService()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_video_text_feed(self):
        """Test case for get_video_text_feed

        """
        pass


if __name__ == '__main__':
    unittest.main()
