"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.report.model.get_real_time_data_response_wrapper_body import GetRealTimeDataResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['GetRealTimeDataResponseWrapperBody'] = GetRealTimeDataResponseWrapperBody
from baiduads.report.model.get_real_time_data_response_wrapper import GetRealTimeDataResponseWrapper


class TestGetRealTimeDataResponseWrapper(unittest.TestCase):
    """GetRealTimeDataResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetRealTimeDataResponseWrapper(self):
        """Test GetRealTimeDataResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetRealTimeDataResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
