"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.rtafeed.model.del_strategy_response_wrapper_body import DelStrategyResponseWrapperBody


class TestDelStrategyResponseWrapperBody(unittest.TestCase):
    """DelStrategyResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDelStrategyResponseWrapperBody(self):
        """Test DelStrategyResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DelStrategyResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
