"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.bulkjob.model.get_changed_scale_co import GetChangedScaleCO
globals()['GetChangedScaleCO'] = GetChangedScaleCO
from baiduads.bulkjob.model.get_changed_scale_response_wrapper_body import GetChangedScaleResponseWrapperBody


class TestGetChangedScaleResponseWrapperBody(unittest.TestCase):
    """GetChangedScaleResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetChangedScaleResponseWrapperBody(self):
        """Test GetChangedScaleResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetChangedScaleResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
