"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.campaignshopping.model.get_product_response_wrapper_body import GetProductResponseWrapperBody
from baiduads.common.model.api_response_header import ApiResponseHeader
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['GetProductResponseWrapperBody'] = GetProductResponseWrapperBody
from baiduads.campaignshopping.model.get_product_response_wrapper import GetProductResponseWrapper


class TestGetProductResponseWrapper(unittest.TestCase):
    """GetProductResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetProductResponseWrapper(self):
        """Test GetProductResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetProductResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
