"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.apidataasset.model.data_asset_task_response import DataAssetTaskResponse
globals()['DataAssetTaskResponse'] = DataAssetTaskResponse
from baiduads.apidataasset.model.submit_data_asset_task_response_wrapper_body import SubmitDataAssetTaskResponseWrapperBody


class TestSubmitDataAssetTaskResponseWrapperBody(unittest.TestCase):
    """SubmitDataAssetTaskResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmitDataAssetTaskResponseWrapperBody(self):
        """Test SubmitDataAssetTaskResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubmitDataAssetTaskResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
