"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_request_header import ApiRequestHeader
from baiduads.crowdbind.model.crowd_bind_mod_request import CrowdBindModRequest
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['CrowdBindModRequest'] = CrowdBindModRequest
from baiduads.crowdbind.model.add_bind_request_wrapper import AddBindRequestWrapper


class TestAddBindRequestWrapper(unittest.TestCase):
    """AddBindRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddBindRequestWrapper(self):
        """Test AddBindRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddBindRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
