"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.productadskeyword.model.pause_keyword_response_wrapper_body import PauseKeywordResponseWrapperBody


class TestPauseKeywordResponseWrapperBody(unittest.TestCase):
    """PauseKeywordResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPauseKeywordResponseWrapperBody(self):
        """Test PauseKeywordResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PauseKeywordResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
