"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.preaudit.model.ad_cont_item_type import AdContItemType


class TestAdContItemType(unittest.TestCase):
    """AdContItemType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdContItemType(self):
        """Test AdContItemType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AdContItemType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
