"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.jmysite.model.jmy_page_id_response import JmyPageIdResponse


class TestJmyPageIdResponse(unittest.TestCase):
    """JmyPageIdResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJmyPageIdResponse(self):
        """Test JmyPageIdResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JmyPageIdResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
