"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.bmcdistribution.model.get_authorized_catalog_response import GetAuthorizedCatalogResponse
globals()['GetAuthorizedCatalogResponse'] = GetAuthorizedCatalogResponse
from baiduads.bmcdistribution.model.get_catalog_response_wrapper_body import GetCatalogResponseWrapperBody


class TestGetCatalogResponseWrapperBody(unittest.TestCase):
    """GetCatalogResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCatalogResponseWrapperBody(self):
        """Test GetCatalogResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCatalogResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
