"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.campaignfeed.model.campaign_feed_type import CampaignFeedType
globals()['CampaignFeedType'] = CampaignFeedType
from baiduads.campaignfeed.model.update_campaign_feed_response_wrapper_body import UpdateCampaignFeedResponseWrapperBody


class TestUpdateCampaignFeedResponseWrapperBody(unittest.TestCase):
    """UpdateCampaignFeedResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateCampaignFeedResponseWrapperBody(self):
        """Test UpdateCampaignFeedResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateCampaignFeedResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
