"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_request_header import ApiRequestHeader
from baiduads.search.model.get_count_by_id_params import GetCountByIdParams
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['GetCountByIdParams'] = GetCountByIdParams
from baiduads.search.model.get_count_by_id_request_wrapper import GetCountByIdRequestWrapper


class TestGetCountByIdRequestWrapper(unittest.TestCase):
    """GetCountByIdRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCountByIdRequestWrapper(self):
        """Test GetCountByIdRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCountByIdRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
