"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.platproduct.model.get_product_list_response_wrapper_body import GetProductListResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['GetProductListResponseWrapperBody'] = GetProductListResponseWrapperBody
from baiduads.platproduct.model.get_product_list_response_wrapper import GetProductListResponseWrapper


class TestGetProductListResponseWrapper(unittest.TestCase):
    """GetProductListResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetProductListResponseWrapper(self):
        """Test GetProductListResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetProductListResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
