"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.shield.model.add_b_shield_policy_response_wrapper_body import AddBShieldPolicyResponseWrapperBody
globals()['AddBShieldPolicyResponseWrapperBody'] = AddBShieldPolicyResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
from baiduads.shield.model.add_b_shield_policy_response_wrapper import AddBShieldPolicyResponseWrapper


class TestAddBShieldPolicyResponseWrapper(unittest.TestCase):
    """AddBShieldPolicyResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddBShieldPolicyResponseWrapper(self):
        """Test AddBShieldPolicyResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddBShieldPolicyResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
