"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.materialquestionmod.model.tesla_question_batch_update_putaway_request import TeslaQuestionBatchUpdatePutawayRequest


class TestTeslaQuestionBatchUpdatePutawayRequest(unittest.TestCase):
    """TeslaQuestionBatchUpdatePutawayRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeslaQuestionBatchUpdatePutawayRequest(self):
        """Test TeslaQuestionBatchUpdatePutawayRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TeslaQuestionBatchUpdatePutawayRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
