"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.materialpersonmod.model.person_detail_dto import PersonDetailDto
globals()['PersonDetailDto'] = PersonDetailDto
from baiduads.materialpersonmod.model.update_person_response_wrapper_body import UpdatePersonResponseWrapperBody


class TestUpdatePersonResponseWrapperBody(unittest.TestCase):
    """UpdatePersonResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdatePersonResponseWrapperBody(self):
        """Test UpdatePersonResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdatePersonResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
