"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.dpaadgroupfeed.model.dpa_ocpc_type import DpaOcpcType


class TestDpaOcpcType(unittest.TestCase):
    """DpaOcpcType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDpaOcpcType(self):
        """Test DpaOcpcType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DpaOcpcType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
