"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.rtafeed.model.get_configurable_users_response_wrapper_body import GetConfigurableUsersResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['GetConfigurableUsersResponseWrapperBody'] = GetConfigurableUsersResponseWrapperBody
from baiduads.rtafeed.model.get_configurable_users_response_wrapper import GetConfigurableUsersResponseWrapper


class TestGetConfigurableUsersResponseWrapper(unittest.TestCase):
    """GetConfigurableUsersResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetConfigurableUsersResponseWrapper(self):
        """Test GetConfigurableUsersResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetConfigurableUsersResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
