"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import unittest

import baiduads
from traceurl.api.trace_url_service import TraceUrlService  # noqa: E501


class TestTraceUrlService(unittest.TestCase):
    """TraceUrlService unit test stubs"""

    def setUp(self):
        self.api = TraceUrlService()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_promotion_urls(self):
        """Test case for get_promotion_urls

        """
        pass


if __name__ == '__main__':
    unittest.main()
