"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.campaignshopping.model.campaign_shopping_type import CampaignShoppingType
globals()['CampaignShoppingType'] = CampaignShoppingType
from baiduads.campaignshopping.model.add_campaign_request import AddCampaignRequest


class TestAddCampaignRequest(unittest.TestCase):
    """AddCampaignRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddCampaignRequest(self):
        """Test AddCampaignRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddCampaignRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
