"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_request_header import ApiRequestHeader
from baiduads.fctranstraceapi.model.fc_trans_trace_del_request import FcTransTraceDelRequest
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['FcTransTraceDelRequest'] = FcTransTraceDelRequest
from baiduads.fctranstraceapi.model.delete_fc_trans_trace_request_wrapper import DeleteFcTransTraceRequestWrapper


class TestDeleteFcTransTraceRequestWrapper(unittest.TestCase):
    """DeleteFcTransTraceRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteFcTransTraceRequestWrapper(self):
        """Test DeleteFcTransTraceRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteFcTransTraceRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
