"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.dpacreative.model.get_creative_group_response_wrapper_body import GetCreativeGroupResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['GetCreativeGroupResponseWrapperBody'] = GetCreativeGroupResponseWrapperBody
from baiduads.dpacreative.model.get_creative_group_response_wrapper import GetCreativeGroupResponseWrapper


class TestGetCreativeGroupResponseWrapper(unittest.TestCase):
    """GetCreativeGroupResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCreativeGroupResponseWrapper(self):
        """Test GetCreativeGroupResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCreativeGroupResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
