"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.materialquestionmod.model.update_putaway_response_wrapper_body import UpdatePutawayResponseWrapperBody


class TestUpdatePutawayResponseWrapperBody(unittest.TestCase):
    """UpdatePutawayResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdatePutawayResponseWrapperBody(self):
        """Test UpdatePutawayResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdatePutawayResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
