"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import unittest

import baiduads
from shield.api.shield_service import ShieldService  # noqa: E501


class TestShieldService(unittest.TestCase):
    """ShieldService unit test stubs"""

    def setUp(self):
        self.api = ShieldService()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_account_exclude_ip(self):
        """Test case for add_account_exclude_ip

        """
        pass

    def test_add_b_shield_policy(self):
        """Test case for add_b_shield_policy

        """
        pass

    def test_del_account_exclude_ip(self):
        """Test case for del_account_exclude_ip

        """
        pass

    def test_delete_b_shield_black_ip(self):
        """Test case for delete_b_shield_black_ip

        """
        pass

    def test_delete_b_shield_customer(self):
        """Test case for delete_b_shield_customer

        """
        pass

    def test_delete_b_shield_policy(self):
        """Test case for delete_b_shield_policy

        """
        pass

    def test_update_b_shield_black_ip(self):
        """Test case for update_b_shield_black_ip

        """
        pass

    def test_update_b_shield_customer(self):
        """Test case for update_b_shield_customer

        """
        pass

    def test_update_policy_ipto_black_ip(self):
        """Test case for update_policy_ipto_black_ip

        """
        pass

    def test_update_shield_policy(self):
        """Test case for update_shield_policy

        """
        pass


if __name__ == '__main__':
    unittest.main()
