"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.campaign.model.api_campaign_add_request import ApiCampaignAddRequest
from baiduads.common.model.api_request_header import ApiRequestHeader
globals()['ApiCampaignAddRequest'] = ApiCampaignAddRequest
globals()['ApiRequestHeader'] = ApiRequestHeader
from baiduads.campaign.model.add_campaign_request_wrapper import AddCampaignRequestWrapper


class TestAddCampaignRequestWrapper(unittest.TestCase):
    """AddCampaignRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddCampaignRequestWrapper(self):
        """Test AddCampaignRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddCampaignRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
