"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import unittest

import baiduads
from bmcproduct.api.bmc_product_service import BmcProductService  # noqa: E501


class TestBmcProductService(unittest.TestCase):
    """BmcProductService unit test stubs"""

    def setUp(self):
        self.api = BmcProductService()  # noqa: E501

    def tearDown(self):
        pass

    def test_fast_update_products(self):
        """Test case for fast_update_products

        """
        pass


if __name__ == '__main__':
    unittest.main()
