"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.openapireport.model.get_report_data_response_wrapper_body import GetReportDataResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['GetReportDataResponseWrapperBody'] = GetReportDataResponseWrapperBody
from baiduads.openapireport.model.get_report_data_response_wrapper import GetReportDataResponseWrapper


class TestGetReportDataResponseWrapper(unittest.TestCase):
    """GetReportDataResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetReportDataResponseWrapper(self):
        """Test GetReportDataResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetReportDataResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
