"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_request_header import ApiRequestHeader
from baiduads.imagemanagement.model.video_extract_request import VideoExtractRequest
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['VideoExtractRequest'] = VideoExtractRequest
from baiduads.imagemanagement.model.get_video_extract_image_request_wrapper import GetVideoExtractImageRequestWrapper


class TestGetVideoExtractImageRequestWrapper(unittest.TestCase):
    """GetVideoExtractImageRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetVideoExtractImageRequestWrapper(self):
        """Test GetVideoExtractImageRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetVideoExtractImageRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
