"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.keyword.model.api_offline_reason import ApiOfflineReason


class TestApiOfflineReason(unittest.TestCase):
    """ApiOfflineReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiOfflineReason(self):
        """Test ApiOfflineReason"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiOfflineReason()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
