"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_request_header import ApiRequestHeader
from baiduads.oauthauthorizedtoolapi.model.authorized_tool_request import AuthorizedToolRequest
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['AuthorizedToolRequest'] = AuthorizedToolRequest
from baiduads.oauthauthorizedtoolapi.model.get_auth_code_request_wrapper import GetAuthCodeRequestWrapper


class TestGetAuthCodeRequestWrapper(unittest.TestCase):
    """GetAuthCodeRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAuthCodeRequestWrapper(self):
        """Test GetAuthCodeRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAuthCodeRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
