"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.accountfeed.model.update_account_feed_response_wrapper_body import UpdateAccountFeedResponseWrapperBody
from baiduads.common.model.api_response_header import ApiResponseHeader
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['UpdateAccountFeedResponseWrapperBody'] = UpdateAccountFeedResponseWrapperBody
from baiduads.accountfeed.model.update_account_feed_response_wrapper import UpdateAccountFeedResponseWrapper


class TestUpdateAccountFeedResponseWrapper(unittest.TestCase):
    """UpdateAccountFeedResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateAccountFeedResponseWrapper(self):
        """Test UpdateAccountFeedResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateAccountFeedResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
