"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.advancedsegmentbind.model.segment_bind_type_api_segment_batch_request import SegmentBindTypeApiSegmentBatchRequest
from baiduads.common.model.api_request_header import ApiRequestHeader
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['SegmentBindTypeApiSegmentBatchRequest'] = SegmentBindTypeApiSegmentBatchRequest
from baiduads.advancedsegmentbind.model.update_segment_bind_request_wrapper import UpdateSegmentBindRequestWrapper


class TestUpdateSegmentBindRequestWrapper(unittest.TestCase):
    """UpdateSegmentBindRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSegmentBindRequestWrapper(self):
        """Test UpdateSegmentBindRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateSegmentBindRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
