"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.imagesegment.model.add_image_segment_response_wrapper_body import AddImageSegmentResponseWrapperBody
globals()['AddImageSegmentResponseWrapperBody'] = AddImageSegmentResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
from baiduads.imagesegment.model.add_image_segment_response_wrapper import AddImageSegmentResponseWrapper


class TestAddImageSegmentResponseWrapper(unittest.TestCase):
    """AddImageSegmentResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddImageSegmentResponseWrapper(self):
        """Test AddImageSegmentResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddImageSegmentResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
