"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.creativefeed.model.pa_picture import PaPicture


class TestPaPicture(unittest.TestCase):
    """PaPicture unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaPicture(self):
        """Test PaPicture"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaPicture()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
