"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.advice.model.advice_summary import AdviceSummary


class TestAdviceSummary(unittest.TestCase):
    """AdviceSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdviceSummary(self):
        """Test AdviceSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AdviceSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
