"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_response_header import ApiResponseHeader
from baiduads.searchfeed.model.get_medias_response_wrapper_body import GetMediasResponseWrapperBody
globals()['ApiResponseHeader'] = ApiResponseHeader
globals()['GetMediasResponseWrapperBody'] = GetMediasResponseWrapperBody
from baiduads.searchfeed.model.get_medias_response_wrapper import GetMediasResponseWrapper


class TestGetMediasResponseWrapper(unittest.TestCase):
    """GetMediasResponseWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetMediasResponseWrapper(self):
        """Test GetMediasResponseWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetMediasResponseWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
