"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.adgroupimagesegmentbind.model.add_adgroup_image_segment_bind_type import AddAdgroupImageSegmentBindType
from baiduads.common.model.api_request_header import ApiRequestHeader
globals()['AddAdgroupImageSegmentBindType'] = AddAdgroupImageSegmentBindType
globals()['ApiRequestHeader'] = ApiRequestHeader
from baiduads.adgroupimagesegmentbind.model.add_adgroup_image_segment_bind_request_wrapper import AddAdgroupImageSegmentBindRequestWrapper


class TestAddAdgroupImageSegmentBindRequestWrapper(unittest.TestCase):
    """AddAdgroupImageSegmentBindRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddAdgroupImageSegmentBindRequestWrapper(self):
        """Test AddAdgroupImageSegmentBindRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddAdgroupImageSegmentBindRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
