"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.platproduct.model.plat_audit_reason_detail_vo import PlatAuditReasonDetailVo


class TestPlatAuditReasonDetailVo(unittest.TestCase):
    """PlatAuditReasonDetailVo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlatAuditReasonDetailVo(self):
        """Test PlatAuditReasonDetailVo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlatAuditReasonDetailVo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
