"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.materialproduct.model.word_count_dto import WordCountDto


class TestWordCountDto(unittest.TestCase):
    """WordCountDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWordCountDto(self):
        """Test WordCountDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WordCountDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
