"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.searchfeed.model.auto_bid_cost_response import AutoBidCostResponse


class TestAutoBidCostResponse(unittest.TestCase):
    """AutoBidCostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutoBidCostResponse(self):
        """Test AutoBidCostResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AutoBidCostResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
