"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.indexapi.model.date_range import DateRange
from baiduads.indexapi.model.region import Region
globals()['DateRange'] = DateRange
globals()['Region'] = Region
from baiduads.indexapi.model.index_task_create_request import IndexTaskCreateRequest


class TestIndexTaskCreateRequest(unittest.TestCase):
    """IndexTaskCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexTaskCreateRequest(self):
        """Test IndexTaskCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndexTaskCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
