"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.imagemanage.model.del_image_response_wrapper_body import DelImageResponseWrapperBody


class TestDelImageResponseWrapperBody(unittest.TestCase):
    """DelImageResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDelImageResponseWrapperBody(self):
        """Test DelImageResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DelImageResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
