"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.shield.model.shield_black_ip_type import ShieldBlackIPType


class TestShieldBlackIPType(unittest.TestCase):
    """ShieldBlackIPType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShieldBlackIPType(self):
        """Test ShieldBlackIPType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ShieldBlackIPType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
