"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_request_header import ApiRequestHeader
from baiduads.search.model.get_tab_params import GetTabParams
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['GetTabParams'] = GetTabParams
from baiduads.search.model.get_tab_request_wrapper import GetTabRequestWrapper


class TestGetTabRequestWrapper(unittest.TestCase):
    """GetTabRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTabRequestWrapper(self):
        """Test GetTabRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTabRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
