"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.apiserviceforexternal.model.pre_datatags_response import PreDatatagsResponse
globals()['PreDatatagsResponse'] = PreDatatagsResponse
from baiduads.apiserviceforexternal.model.create_data_tags_response_wrapper_body import CreateDataTagsResponseWrapperBody


class TestCreateDataTagsResponseWrapperBody(unittest.TestCase):
    """CreateDataTagsResponseWrapperBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateDataTagsResponseWrapperBody(self):
        """Test CreateDataTagsResponseWrapperBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateDataTagsResponseWrapperBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
