"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

    The version of the OpenAPI document: 1.0.1-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import baiduads
from baiduads.common.model.api_request_header import ApiRequestHeader
from baiduads.ocpc.model.mod_package_request import ModPackageRequest
globals()['ApiRequestHeader'] = ApiRequestHeader
globals()['ModPackageRequest'] = ModPackageRequest
from baiduads.ocpc.model.update_target_package_request_wrapper import UpdateTargetPackageRequestWrapper


class TestUpdateTargetPackageRequestWrapper(unittest.TestCase):
    """UpdateTargetPackageRequestWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateTargetPackageRequestWrapper(self):
        """Test UpdateTargetPackageRequestWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateTargetPackageRequestWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
