/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.platorderbusinessquery.model;

import com.baidu.dev2.api.sdk.platorderbusinessquery.model.PlatLifeServiceUserAddress;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlatAppointmentVo
 */
public class PlatAppointmentVoTest {
    private final PlatAppointmentVo model = new PlatAppointmentVo();

    /**
     * Model tests for PlatAppointmentVo
     */
    @Test
    public void testPlatAppointmentVo() {
        // TODO: test PlatAppointmentVo
    }

    /**
     * Test the property 'startAddress'
     */
    @Test
    public void startAddressTest() {
        // TODO: test startAddress
    }

    /**
     * Test the property 'endAddress'
     */
    @Test
    public void endAddressTest() {
        // TODO: test endAddress
    }

    /**
     * Test the property 'appointmentTime'
     */
    @Test
    public void appointmentTimeTest() {
        // TODO: test appointmentTime
    }

    /**
     * Test the property 'fromAddr'
     */
    @Test
    public void fromAddrTest() {
        // TODO: test fromAddr
    }

    /**
     * Test the property 'toAddr'
     */
    @Test
    public void toAddrTest() {
        // TODO: test toAddr
    }

}
