/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.leadsnotice.model;

import java.util.Objects;
import java.util.Arrays;
import com.baidu.dev2.api.sdk.leadsnotice.model.NoticeReponse;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NoticeListResponse
 */
@JsonPropertyOrder({
  NoticeListResponse.JSON_PROPERTY_TOTAL_NUM,
  NoticeListResponse.JSON_PROPERTY_ROW_NUMBER,
  NoticeListResponse.JSON_PROPERTY_NOTICE_DETAIL_LIST
})
@JsonTypeName("NoticeListResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class NoticeListResponse {
  public static final String JSON_PROPERTY_TOTAL_NUM = "totalNum";
  private Long totalNum;

  public static final String JSON_PROPERTY_ROW_NUMBER = "rowNumber";
  private Integer rowNumber;

  public static final String JSON_PROPERTY_NOTICE_DETAIL_LIST = "noticeDetailList";
  private List<NoticeReponse> noticeDetailList = null;

  public NoticeListResponse() { 
  }

  public NoticeListResponse totalNum(Long totalNum) {
    
    this.totalNum = totalNum;
    return this;
  }

   /**
   * Get totalNum
   * @return totalNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalNum() {
    return totalNum;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalNum(Long totalNum) {
    this.totalNum = totalNum;
  }


  public NoticeListResponse rowNumber(Integer rowNumber) {
    
    this.rowNumber = rowNumber;
    return this;
  }

   /**
   * Get rowNumber
   * @return rowNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROW_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRowNumber() {
    return rowNumber;
  }


  @JsonProperty(JSON_PROPERTY_ROW_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRowNumber(Integer rowNumber) {
    this.rowNumber = rowNumber;
  }


  public NoticeListResponse noticeDetailList(List<NoticeReponse> noticeDetailList) {
    
    this.noticeDetailList = noticeDetailList;
    return this;
  }

  public NoticeListResponse addNoticeDetailListItem(NoticeReponse noticeDetailListItem) {
    if (this.noticeDetailList == null) {
      this.noticeDetailList = new ArrayList<>();
    }
    this.noticeDetailList.add(noticeDetailListItem);
    return this;
  }

   /**
   * Get noticeDetailList
   * @return noticeDetailList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NOTICE_DETAIL_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NoticeReponse> getNoticeDetailList() {
    return noticeDetailList;
  }


  @JsonProperty(JSON_PROPERTY_NOTICE_DETAIL_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoticeDetailList(List<NoticeReponse> noticeDetailList) {
    this.noticeDetailList = noticeDetailList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NoticeListResponse noticeListResponse = (NoticeListResponse) o;
    return Objects.equals(this.totalNum, noticeListResponse.totalNum) &&
        Objects.equals(this.rowNumber, noticeListResponse.rowNumber) &&
        Objects.equals(this.noticeDetailList, noticeListResponse.noticeDetailList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalNum, rowNumber, noticeDetailList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NoticeListResponse {\n");
    sb.append("    totalNum: ").append(toIndentedString(totalNum)).append("\n");
    sb.append("    rowNumber: ").append(toIndentedString(rowNumber)).append("\n");
    sb.append("    noticeDetailList: ").append(toIndentedString(noticeDetailList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

