/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.crowdfeed.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CrowdFeedType
 */
@JsonPropertyOrder({
  CrowdFeedType.JSON_PROPERTY_CROWD_ID,
  CrowdFeedType.JSON_PROPERTY_CROWD_NAME
})
@JsonTypeName("CrowdFeedType")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CrowdFeedType {
  public static final String JSON_PROPERTY_CROWD_ID = "crowdId";
  private Long crowdId;

  public static final String JSON_PROPERTY_CROWD_NAME = "crowdName";
  private String crowdName;

  public CrowdFeedType() { 
  }

  public CrowdFeedType crowdId(Long crowdId) {
    
    this.crowdId = crowdId;
    return this;
  }

   /**
   * Get crowdId
   * @return crowdId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CROWD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCrowdId() {
    return crowdId;
  }


  @JsonProperty(JSON_PROPERTY_CROWD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCrowdId(Long crowdId) {
    this.crowdId = crowdId;
  }


  public CrowdFeedType crowdName(String crowdName) {
    
    this.crowdName = crowdName;
    return this;
  }

   /**
   * Get crowdName
   * @return crowdName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CROWD_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCrowdName() {
    return crowdName;
  }


  @JsonProperty(JSON_PROPERTY_CROWD_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCrowdName(String crowdName) {
    this.crowdName = crowdName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CrowdFeedType crowdFeedType = (CrowdFeedType) o;
    return Objects.equals(this.crowdId, crowdFeedType.crowdId) &&
        Objects.equals(this.crowdName, crowdFeedType.crowdName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(crowdId, crowdName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CrowdFeedType {\n");
    sb.append("    crowdId: ").append(toIndentedString(crowdId)).append("\n");
    sb.append("    crowdName: ").append(toIndentedString(crowdName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

