/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.baidu.dev2.api.sdk.leadads.api;

import com.fasterxml.jackson.core.type.TypeReference;

import com.baidu.dev2.api.sdk.invoke.ApiException;
import com.baidu.dev2.api.sdk.invoke.ApiClient;
import com.baidu.dev2.api.sdk.invoke.Configuration;
import com.baidu.dev2.api.sdk.leadads.model.*;
import com.baidu.dev2.api.sdk.invoke.Pair;

import com.baidu.dev2.api.sdk.leadads.model.AddStrategiesRequestWrapper;
import com.baidu.dev2.api.sdk.leadads.model.AddStrategiesResponseWrapper;
import com.baidu.dev2.api.sdk.leadads.model.DeleteStrategiesRequestWrapper;
import com.baidu.dev2.api.sdk.leadads.model.DeleteStrategiesResponseWrapper;
import com.baidu.dev2.api.sdk.leadads.model.GetMaterialsRequestWrapper;
import com.baidu.dev2.api.sdk.leadads.model.GetMaterialsResponseWrapper;
import com.baidu.dev2.api.sdk.leadads.model.GetStrategiesRequestWrapper;
import com.baidu.dev2.api.sdk.leadads.model.GetStrategiesResponseWrapper;
import com.baidu.dev2.api.sdk.leadads.model.UpdateStrategiesRequestWrapper;
import com.baidu.dev2.api.sdk.leadads.model.UpdateStrategiesResponseWrapper;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LeadAdsService {
  private ApiClient apiClient;

  public LeadAdsService() {
    this(Configuration.getDefaultApiClient());
  }

  public LeadAdsService(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  public ApiClient getApiClient() {
    return apiClient;
  }

  public void setApiClient(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * 
   * 
   * @param addStrategiesRequestWrapper  (required)
   * @return AddStrategiesResponseWrapper
   * @throws ApiException if fails to make API call
   */
  public AddStrategiesResponseWrapper addStrategies(AddStrategiesRequestWrapper addStrategiesRequestWrapper) throws ApiException {
    Object localVarPostBody = addStrategiesRequestWrapper;
    
    // verify the required parameter 'addStrategiesRequestWrapper' is set
    if (addStrategiesRequestWrapper == null) {
      throw new ApiException(400, "Missing the required parameter 'addStrategiesRequestWrapper' when calling addStrategies");
    }
    
    // create path and map variables
    String localVarPath = "/json/sms/service/LeadAdsService/addStrategies";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json;charset=UTF-8"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json;charset=UTF-8"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] {  };

    TypeReference<AddStrategiesResponseWrapper> localVarReturnType = new TypeReference<AddStrategiesResponseWrapper>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
  /**
   * 
   * 
   * @param deleteStrategiesRequestWrapper  (required)
   * @return DeleteStrategiesResponseWrapper
   * @throws ApiException if fails to make API call
   */
  public DeleteStrategiesResponseWrapper deleteStrategies(DeleteStrategiesRequestWrapper deleteStrategiesRequestWrapper) throws ApiException {
    Object localVarPostBody = deleteStrategiesRequestWrapper;
    
    // verify the required parameter 'deleteStrategiesRequestWrapper' is set
    if (deleteStrategiesRequestWrapper == null) {
      throw new ApiException(400, "Missing the required parameter 'deleteStrategiesRequestWrapper' when calling deleteStrategies");
    }
    
    // create path and map variables
    String localVarPath = "/json/sms/service/LeadAdsService/deleteStrategies";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json;charset=UTF-8"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json;charset=UTF-8"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] {  };

    TypeReference<DeleteStrategiesResponseWrapper> localVarReturnType = new TypeReference<DeleteStrategiesResponseWrapper>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
  /**
   * 
   * 
   * @param getMaterialsRequestWrapper  (required)
   * @return GetMaterialsResponseWrapper
   * @throws ApiException if fails to make API call
   */
  public GetMaterialsResponseWrapper getMaterials(GetMaterialsRequestWrapper getMaterialsRequestWrapper) throws ApiException {
    Object localVarPostBody = getMaterialsRequestWrapper;
    
    // verify the required parameter 'getMaterialsRequestWrapper' is set
    if (getMaterialsRequestWrapper == null) {
      throw new ApiException(400, "Missing the required parameter 'getMaterialsRequestWrapper' when calling getMaterials");
    }
    
    // create path and map variables
    String localVarPath = "/json/sms/service/LeadAdsService/getMaterials";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json;charset=UTF-8"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json;charset=UTF-8"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] {  };

    TypeReference<GetMaterialsResponseWrapper> localVarReturnType = new TypeReference<GetMaterialsResponseWrapper>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
  /**
   * 
   * 
   * @param getStrategiesRequestWrapper  (required)
   * @return GetStrategiesResponseWrapper
   * @throws ApiException if fails to make API call
   */
  public GetStrategiesResponseWrapper getStrategies(GetStrategiesRequestWrapper getStrategiesRequestWrapper) throws ApiException {
    Object localVarPostBody = getStrategiesRequestWrapper;
    
    // verify the required parameter 'getStrategiesRequestWrapper' is set
    if (getStrategiesRequestWrapper == null) {
      throw new ApiException(400, "Missing the required parameter 'getStrategiesRequestWrapper' when calling getStrategies");
    }
    
    // create path and map variables
    String localVarPath = "/json/sms/service/LeadAdsService/getStrategies";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json;charset=UTF-8"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json;charset=UTF-8"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] {  };

    TypeReference<GetStrategiesResponseWrapper> localVarReturnType = new TypeReference<GetStrategiesResponseWrapper>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
  /**
   * 
   * 
   * @param updateStrategiesRequestWrapper  (required)
   * @return UpdateStrategiesResponseWrapper
   * @throws ApiException if fails to make API call
   */
  public UpdateStrategiesResponseWrapper updateStrategies(UpdateStrategiesRequestWrapper updateStrategiesRequestWrapper) throws ApiException {
    Object localVarPostBody = updateStrategiesRequestWrapper;
    
    // verify the required parameter 'updateStrategiesRequestWrapper' is set
    if (updateStrategiesRequestWrapper == null) {
      throw new ApiException(400, "Missing the required parameter 'updateStrategiesRequestWrapper' when calling updateStrategies");
    }
    
    // create path and map variables
    String localVarPath = "/json/sms/service/LeadAdsService/updateStrategies";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json;charset=UTF-8"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json;charset=UTF-8"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] {  };

    TypeReference<UpdateStrategiesResponseWrapper> localVarReturnType = new TypeReference<UpdateStrategiesResponseWrapper>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
}
