/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.advice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AdviceQueryRequest
 */
@JsonPropertyOrder({
  AdviceQueryRequest.JSON_PROPERTY_ADVICE_KEYS
})
@JsonTypeName("AdviceQueryRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AdviceQueryRequest {
  public static final String JSON_PROPERTY_ADVICE_KEYS = "adviceKeys";
  private List<String> adviceKeys = null;

  public AdviceQueryRequest() { 
  }

  public AdviceQueryRequest adviceKeys(List<String> adviceKeys) {
    
    this.adviceKeys = adviceKeys;
    return this;
  }

  public AdviceQueryRequest addAdviceKeysItem(String adviceKeysItem) {
    if (this.adviceKeys == null) {
      this.adviceKeys = new ArrayList<>();
    }
    this.adviceKeys.add(adviceKeysItem);
    return this;
  }

   /**
   * Get adviceKeys
   * @return adviceKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADVICE_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAdviceKeys() {
    return adviceKeys;
  }


  @JsonProperty(JSON_PROPERTY_ADVICE_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdviceKeys(List<String> adviceKeys) {
    this.adviceKeys = adviceKeys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdviceQueryRequest adviceQueryRequest = (AdviceQueryRequest) o;
    return Objects.equals(this.adviceKeys, adviceQueryRequest.adviceKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adviceKeys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdviceQueryRequest {\n");
    sb.append("    adviceKeys: ").append(toIndentedString(adviceKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

