# coding: utf-8

# flake8: noqa
"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from baiduads.adgroup.model.add_adgroup_request_wrapper import AddAdgroupRequestWrapper
from baiduads.adgroup.model.add_adgroup_response_wrapper import AddAdgroupResponseWrapper
from baiduads.adgroup.model.add_adgroup_response_wrapper_body import AddAdgroupResponseWrapperBody
from baiduads.adgroup.model.api_adgroup_add_request import ApiAdgroupAddRequest
from baiduads.adgroup.model.api_adgroup_del_request import ApiAdgroupDelRequest
from baiduads.adgroup.model.api_adgroup_query_request import ApiAdgroupQueryRequest
from baiduads.adgroup.model.api_adgroup_type import ApiAdgroupType
from baiduads.adgroup.model.api_adgroup_update_request import ApiAdgroupUpdateRequest
from baiduads.adgroup.model.delete_adgroup_request_wrapper import DeleteAdgroupRequestWrapper
from baiduads.adgroup.model.delete_adgroup_response_wrapper import DeleteAdgroupResponseWrapper
from baiduads.adgroup.model.delete_adgroup_response_wrapper_body import DeleteAdgroupResponseWrapperBody
from baiduads.adgroup.model.get_adgroup_request_wrapper import GetAdgroupRequestWrapper
from baiduads.adgroup.model.get_adgroup_response_wrapper import GetAdgroupResponseWrapper
from baiduads.adgroup.model.get_adgroup_response_wrapper_body import GetAdgroupResponseWrapperBody
from baiduads.adgroup.model.update_adgroup_request_wrapper import UpdateAdgroupRequestWrapper
from baiduads.adgroup.model.update_adgroup_response_wrapper import UpdateAdgroupResponseWrapper
from baiduads.adgroup.model.update_adgroup_response_wrapper_body import UpdateAdgroupResponseWrapperBody
