/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.advicesetting.model;

import java.util.Objects;
import java.util.Arrays;
import com.baidu.dev2.api.sdk.advicesetting.model.AdviceSettingType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AdviceSettingTypeCommonBatchRequest
 */
@JsonPropertyOrder({
  AdviceSettingTypeCommonBatchRequest.JSON_PROPERTY_ITEMS
})
@JsonTypeName("AdviceSettingTypeCommonBatchRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AdviceSettingTypeCommonBatchRequest {
  public static final String JSON_PROPERTY_ITEMS = "items";
  private List<AdviceSettingType> items = null;

  public AdviceSettingTypeCommonBatchRequest() { 
  }

  public AdviceSettingTypeCommonBatchRequest items(List<AdviceSettingType> items) {
    
    this.items = items;
    return this;
  }

  public AdviceSettingTypeCommonBatchRequest addItemsItem(AdviceSettingType itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AdviceSettingType> getItems() {
    return items;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItems(List<AdviceSettingType> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdviceSettingTypeCommonBatchRequest adviceSettingTypeCommonBatchRequest = (AdviceSettingTypeCommonBatchRequest) o;
    return Objects.equals(this.items, adviceSettingTypeCommonBatchRequest.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdviceSettingTypeCommonBatchRequest {\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

