/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 * The version of the OpenAPI document: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.newcreative.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DpaBasicCreativeType
 */
public class DpaBasicCreativeTypeTest {
    private final DpaBasicCreativeType model = new DpaBasicCreativeType();

    /**
     * Model tests for DpaBasicCreativeType
     */
    @Test
    public void testDpaBasicCreativeType() {
        // TODO: test DpaBasicCreativeType
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'desc'
     */
    @Test
    public void descTest() {
        // TODO: test desc
    }

    /**
     * Test the property 'pcLinkUrl'
     */
    @Test
    public void pcLinkUrlTest() {
        // TODO: test pcLinkUrl
    }

    /**
     * Test the property 'wirelessLinkUrl'
     */
    @Test
    public void wirelessLinkUrlTest() {
        // TODO: test wirelessLinkUrl
    }

    /**
     * Test the property 'wirelessLinkUrlBoxApp'
     */
    @Test
    public void wirelessLinkUrlBoxAppTest() {
        // TODO: test wirelessLinkUrlBoxApp
    }

    /**
     * Test the property 'wirelessLinkUrlDeepLink'
     */
    @Test
    public void wirelessLinkUrlDeepLinkTest() {
        // TODO: test wirelessLinkUrlDeepLink
    }

}
