/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.fmleadsupdate.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * LeadsMark
 */
@JsonPropertyOrder({
  LeadsMark.JSON_PROPERTY_CLUE_ID,
  LeadsMark.JSON_PROPERTY_MARK_TYPE
})
@JsonTypeName("LeadsMark")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LeadsMark {
  public static final String JSON_PROPERTY_CLUE_ID = "clueId";
  private String clueId;

  public static final String JSON_PROPERTY_MARK_TYPE = "markType";
  private Integer markType;

  public LeadsMark() { 
  }

  public LeadsMark clueId(String clueId) {
    
    this.clueId = clueId;
    return this;
  }

   /**
   * Get clueId
   * @return clueId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CLUE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClueId() {
    return clueId;
  }


  @JsonProperty(JSON_PROPERTY_CLUE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClueId(String clueId) {
    this.clueId = clueId;
  }


  public LeadsMark markType(Integer markType) {
    
    this.markType = markType;
    return this;
  }

   /**
   * Get markType
   * @return markType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MARK_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMarkType() {
    return markType;
  }


  @JsonProperty(JSON_PROPERTY_MARK_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarkType(Integer markType) {
    this.markType = markType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LeadsMark leadsMark = (LeadsMark) o;
    return Objects.equals(this.clueId, leadsMark.clueId) &&
        Objects.equals(this.markType, leadsMark.markType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clueId, markType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LeadsMark {\n");
    sb.append("    clueId: ").append(toIndentedString(clueId)).append("\n");
    sb.append("    markType: ").append(toIndentedString(markType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

