/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.platproduct.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlatProductGetListRequest
 */
public class PlatProductGetListRequestTest {
    private final PlatProductGetListRequest model = new PlatProductGetListRequest();

    /**
     * Model tests for PlatProductGetListRequest
     */
    @Test
    public void testPlatProductGetListRequest() {
        // TODO: test PlatProductGetListRequest
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'shopId'
     */
    @Test
    public void shopIdTest() {
        // TODO: test shopId
    }

    /**
     * Test the property 'pageNum'
     */
    @Test
    public void pageNumTest() {
        // TODO: test pageNum
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

}
