/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.rtafeed.model;

import java.util.Objects;
import java.util.Arrays;
import com.baidu.dev2.api.sdk.rtafeed.model.RtaSettingType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RtaSettingTypes
 */
@JsonPropertyOrder({
  RtaSettingTypes.JSON_PROPERTY_TOTAL,
  RtaSettingTypes.JSON_PROPERTY_RTA_SETTING_TYPES
})
@JsonTypeName("RtaSettingTypes")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RtaSettingTypes {
  public static final String JSON_PROPERTY_TOTAL = "total";
  private Integer total;

  public static final String JSON_PROPERTY_RTA_SETTING_TYPES = "rtaSettingTypes";
  private List<RtaSettingType> rtaSettingTypes = null;

  public RtaSettingTypes() { 
  }

  public RtaSettingTypes total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotal() {
    return total;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotal(Integer total) {
    this.total = total;
  }


  public RtaSettingTypes rtaSettingTypes(List<RtaSettingType> rtaSettingTypes) {
    
    this.rtaSettingTypes = rtaSettingTypes;
    return this;
  }

  public RtaSettingTypes addRtaSettingTypesItem(RtaSettingType rtaSettingTypesItem) {
    if (this.rtaSettingTypes == null) {
      this.rtaSettingTypes = new ArrayList<>();
    }
    this.rtaSettingTypes.add(rtaSettingTypesItem);
    return this;
  }

   /**
   * Get rtaSettingTypes
   * @return rtaSettingTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RTA_SETTING_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RtaSettingType> getRtaSettingTypes() {
    return rtaSettingTypes;
  }


  @JsonProperty(JSON_PROPERTY_RTA_SETTING_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRtaSettingTypes(List<RtaSettingType> rtaSettingTypes) {
    this.rtaSettingTypes = rtaSettingTypes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RtaSettingTypes rtaSettingTypes = (RtaSettingTypes) o;
    return Objects.equals(this.total, rtaSettingTypes.total) &&
        Objects.equals(this.rtaSettingTypes, rtaSettingTypes.rtaSettingTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, rtaSettingTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RtaSettingTypes {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    rtaSettingTypes: ").append(toIndentedString(rtaSettingTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

