/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 * The version of the OpenAPI document: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.accountfeed.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RtaFeedSetting
 */
public class RtaFeedSettingTest {
    private final RtaFeedSetting model = new RtaFeedSetting();

    /**
     * Model tests for RtaFeedSetting
     */
    @Test
    public void testRtaFeedSetting() {
        // TODO: test RtaFeedSetting
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'qps'
     */
    @Test
    public void qpsTest() {
        // TODO: test qps
    }

    /**
     * Test the property 'cacheTime'
     */
    @Test
    public void cacheTimeTest() {
        // TODO: test cacheTime
    }

    /**
     * Test the property 'strategyIds'
     */
    @Test
    public void strategyIdsTest() {
        // TODO: test strategyIds
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'customToken'
     */
    @Test
    public void customTokenTest() {
        // TODO: test customToken
    }

    /**
     * Test the property 'requestTimeoutStrategy'
     */
    @Test
    public void requestTimeoutStrategyTest() {
        // TODO: test requestTimeoutStrategy
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
