/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.shieldfunction.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AddIPBlackManualRequest
 */
@JsonPropertyOrder({
  AddIPBlackManualRequest.JSON_PROPERTY_IP_BLACK
})
@JsonTypeName("AddIPBlackManualRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AddIPBlackManualRequest {
  public static final String JSON_PROPERTY_IP_BLACK = "ipBlack";
  private List<String> ipBlack = null;

  public AddIPBlackManualRequest() { 
  }

  public AddIPBlackManualRequest ipBlack(List<String> ipBlack) {
    
    this.ipBlack = ipBlack;
    return this;
  }

  public AddIPBlackManualRequest addIpBlackItem(String ipBlackItem) {
    if (this.ipBlack == null) {
      this.ipBlack = new ArrayList<>();
    }
    this.ipBlack.add(ipBlackItem);
    return this;
  }

   /**
   * Get ipBlack
   * @return ipBlack
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IP_BLACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getIpBlack() {
    return ipBlack;
  }


  @JsonProperty(JSON_PROPERTY_IP_BLACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpBlack(List<String> ipBlack) {
    this.ipBlack = ipBlack;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddIPBlackManualRequest addIPBlackManualRequest = (AddIPBlackManualRequest) o;
    return Objects.equals(this.ipBlack, addIPBlackManualRequest.ipBlack);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ipBlack);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddIPBlackManualRequest {\n");
    sb.append("    ipBlack: ").append(toIndentedString(ipBlack)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

