/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.search.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetMaterialInfoBySearchParams
 */
@JsonPropertyOrder({
  GetMaterialInfoBySearchParams.JSON_PROPERTY_SEARCH_WORD,
  GetMaterialInfoBySearchParams.JSON_PROPERTY_START_NUM,
  GetMaterialInfoBySearchParams.JSON_PROPERTY_END_NUM,
  GetMaterialInfoBySearchParams.JSON_PROPERTY_CAMPAIGN_ID,
  GetMaterialInfoBySearchParams.JSON_PROPERTY_ADGROUP_ID,
  GetMaterialInfoBySearchParams.JSON_PROPERTY_SEARCH_TYPE,
  GetMaterialInfoBySearchParams.JSON_PROPERTY_SEARCH_LEVEL,
  GetMaterialInfoBySearchParams.JSON_PROPERTY_MATERIAL_FIELDS
})
@JsonTypeName("GetMaterialInfoBySearchParams")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetMaterialInfoBySearchParams {
  public static final String JSON_PROPERTY_SEARCH_WORD = "searchWord";
  private String searchWord;

  public static final String JSON_PROPERTY_START_NUM = "startNum";
  private Integer startNum;

  public static final String JSON_PROPERTY_END_NUM = "endNum";
  private Integer endNum;

  public static final String JSON_PROPERTY_CAMPAIGN_ID = "campaignId";
  private Long campaignId;

  public static final String JSON_PROPERTY_ADGROUP_ID = "adgroupId";
  private Long adgroupId;

  public static final String JSON_PROPERTY_SEARCH_TYPE = "searchType";
  private Integer searchType;

  public static final String JSON_PROPERTY_SEARCH_LEVEL = "searchLevel";
  private Integer searchLevel;

  public static final String JSON_PROPERTY_MATERIAL_FIELDS = "materialFields";
  private List<String> materialFields = null;

  public GetMaterialInfoBySearchParams() { 
  }

  public GetMaterialInfoBySearchParams searchWord(String searchWord) {
    
    this.searchWord = searchWord;
    return this;
  }

   /**
   * Get searchWord
   * @return searchWord
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SEARCH_WORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSearchWord() {
    return searchWord;
  }


  @JsonProperty(JSON_PROPERTY_SEARCH_WORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchWord(String searchWord) {
    this.searchWord = searchWord;
  }


  public GetMaterialInfoBySearchParams startNum(Integer startNum) {
    
    this.startNum = startNum;
    return this;
  }

   /**
   * Get startNum
   * @return startNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_START_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStartNum() {
    return startNum;
  }


  @JsonProperty(JSON_PROPERTY_START_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartNum(Integer startNum) {
    this.startNum = startNum;
  }


  public GetMaterialInfoBySearchParams endNum(Integer endNum) {
    
    this.endNum = endNum;
    return this;
  }

   /**
   * Get endNum
   * @return endNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_END_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEndNum() {
    return endNum;
  }


  @JsonProperty(JSON_PROPERTY_END_NUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndNum(Integer endNum) {
    this.endNum = endNum;
  }


  public GetMaterialInfoBySearchParams campaignId(Long campaignId) {
    
    this.campaignId = campaignId;
    return this;
  }

   /**
   * Get campaignId
   * @return campaignId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CAMPAIGN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCampaignId() {
    return campaignId;
  }


  @JsonProperty(JSON_PROPERTY_CAMPAIGN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampaignId(Long campaignId) {
    this.campaignId = campaignId;
  }


  public GetMaterialInfoBySearchParams adgroupId(Long adgroupId) {
    
    this.adgroupId = adgroupId;
    return this;
  }

   /**
   * Get adgroupId
   * @return adgroupId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADGROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAdgroupId() {
    return adgroupId;
  }


  @JsonProperty(JSON_PROPERTY_ADGROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdgroupId(Long adgroupId) {
    this.adgroupId = adgroupId;
  }


  public GetMaterialInfoBySearchParams searchType(Integer searchType) {
    
    this.searchType = searchType;
    return this;
  }

   /**
   * Get searchType
   * @return searchType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SEARCH_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSearchType() {
    return searchType;
  }


  @JsonProperty(JSON_PROPERTY_SEARCH_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchType(Integer searchType) {
    this.searchType = searchType;
  }


  public GetMaterialInfoBySearchParams searchLevel(Integer searchLevel) {
    
    this.searchLevel = searchLevel;
    return this;
  }

   /**
   * Get searchLevel
   * @return searchLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SEARCH_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSearchLevel() {
    return searchLevel;
  }


  @JsonProperty(JSON_PROPERTY_SEARCH_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchLevel(Integer searchLevel) {
    this.searchLevel = searchLevel;
  }


  public GetMaterialInfoBySearchParams materialFields(List<String> materialFields) {
    
    this.materialFields = materialFields;
    return this;
  }

  public GetMaterialInfoBySearchParams addMaterialFieldsItem(String materialFieldsItem) {
    if (this.materialFields == null) {
      this.materialFields = new ArrayList<>();
    }
    this.materialFields.add(materialFieldsItem);
    return this;
  }

   /**
   * Get materialFields
   * @return materialFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MATERIAL_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getMaterialFields() {
    return materialFields;
  }


  @JsonProperty(JSON_PROPERTY_MATERIAL_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaterialFields(List<String> materialFields) {
    this.materialFields = materialFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMaterialInfoBySearchParams getMaterialInfoBySearchParams = (GetMaterialInfoBySearchParams) o;
    return Objects.equals(this.searchWord, getMaterialInfoBySearchParams.searchWord) &&
        Objects.equals(this.startNum, getMaterialInfoBySearchParams.startNum) &&
        Objects.equals(this.endNum, getMaterialInfoBySearchParams.endNum) &&
        Objects.equals(this.campaignId, getMaterialInfoBySearchParams.campaignId) &&
        Objects.equals(this.adgroupId, getMaterialInfoBySearchParams.adgroupId) &&
        Objects.equals(this.searchType, getMaterialInfoBySearchParams.searchType) &&
        Objects.equals(this.searchLevel, getMaterialInfoBySearchParams.searchLevel) &&
        Objects.equals(this.materialFields, getMaterialInfoBySearchParams.materialFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(searchWord, startNum, endNum, campaignId, adgroupId, searchType, searchLevel, materialFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMaterialInfoBySearchParams {\n");
    sb.append("    searchWord: ").append(toIndentedString(searchWord)).append("\n");
    sb.append("    startNum: ").append(toIndentedString(startNum)).append("\n");
    sb.append("    endNum: ").append(toIndentedString(endNum)).append("\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    adgroupId: ").append(toIndentedString(adgroupId)).append("\n");
    sb.append("    searchType: ").append(toIndentedString(searchType)).append("\n");
    sb.append("    searchLevel: ").append(toIndentedString(searchLevel)).append("\n");
    sb.append("    materialFields: ").append(toIndentedString(materialFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

