/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 * The version of the OpenAPI document: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.reportfeed.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RealTimeResultTypeFeed
 */
public class RealTimeResultTypeFeedTest {
    private final RealTimeResultTypeFeed model = new RealTimeResultTypeFeed();

    /**
     * Model tests for RealTimeResultTypeFeed
     */
    @Test
    public void testRealTimeResultTypeFeed() {
        // TODO: test RealTimeResultTypeFeed
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'relatedId'
     */
    @Test
    public void relatedIdTest() {
        // TODO: test relatedId
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'relateIdsList'
     */
    @Test
    public void relateIdsListTest() {
        // TODO: test relateIdsList
    }

    /**
     * Test the property 'kpis'
     */
    @Test
    public void kpisTest() {
        // TODO: test kpis
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'totalRowNumber'
     */
    @Test
    public void totalRowNumberTest() {
        // TODO: test totalRowNumber
    }

    /**
     * Test the property 'pageIndex'
     */
    @Test
    public void pageIndexTest() {
        // TODO: test pageIndex
    }

}
