/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.apidataasset.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AssetTag
 */
@JsonPropertyOrder({
  AssetTag.JSON_PROPERTY_DATA_NAME,
  AssetTag.JSON_PROPERTY_SHOW_NAME,
  AssetTag.JSON_PROPERTY_TYPE
})
@JsonTypeName("AssetTag")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AssetTag {
  public static final String JSON_PROPERTY_DATA_NAME = "dataName";
  private String dataName;

  public static final String JSON_PROPERTY_SHOW_NAME = "showName";
  private String showName;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public AssetTag() { 
  }

  public AssetTag dataName(String dataName) {
    
    this.dataName = dataName;
    return this;
  }

   /**
   * Get dataName
   * @return dataName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDataName() {
    return dataName;
  }


  @JsonProperty(JSON_PROPERTY_DATA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataName(String dataName) {
    this.dataName = dataName;
  }


  public AssetTag showName(String showName) {
    
    this.showName = showName;
    return this;
  }

   /**
   * Get showName
   * @return showName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHOW_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShowName() {
    return showName;
  }


  @JsonProperty(JSON_PROPERTY_SHOW_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowName(String showName) {
    this.showName = showName;
  }


  public AssetTag type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetTag assetTag = (AssetTag) o;
    return Objects.equals(this.dataName, assetTag.dataName) &&
        Objects.equals(this.showName, assetTag.showName) &&
        Objects.equals(this.type, assetTag.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataName, showName, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetTag {\n");
    sb.append("    dataName: ").append(toIndentedString(dataName)).append("\n");
    sb.append("    showName: ").append(toIndentedString(showName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

