/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 * The version of the OpenAPI document: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.productadskeyword.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for KeywordType
 */
public class KeywordTypeTest {
    private final KeywordType model = new KeywordType();

    /**
     * Model tests for KeywordType
     */
    @Test
    public void testKeywordType() {
        // TODO: test KeywordType
    }

    /**
     * Test the property 'keywordId'
     */
    @Test
    public void keywordIdTest() {
        // TODO: test keywordId
    }

    /**
     * Test the property 'adgroupId'
     */
    @Test
    public void adgroupIdTest() {
        // TODO: test adgroupId
    }

    /**
     * Test the property 'campaignId'
     */
    @Test
    public void campaignIdTest() {
        // TODO: test campaignId
    }

    /**
     * Test the property 'keyword'
     */
    @Test
    public void keywordTest() {
        // TODO: test keyword
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'targetUrl'
     */
    @Test
    public void targetUrlTest() {
        // TODO: test targetUrl
    }

    /**
     * Test the property 'matchType'
     */
    @Test
    public void matchTypeTest() {
        // TODO: test matchType
    }

    /**
     * Test the property 'winfoType'
     */
    @Test
    public void winfoTypeTest() {
        // TODO: test winfoType
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
