/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 * The version of the OpenAPI document: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.campaign.model;

import com.baidu.dev2.api.sdk.campaign.model.UpdateCampaignResponseWrapperBody;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetCampaignResponseWrapper
 */
public class GetCampaignResponseWrapperTest {
    private final GetCampaignResponseWrapper model = new GetCampaignResponseWrapper();

    /**
     * Model tests for GetCampaignResponseWrapper
     */
    @Test
    public void testGetCampaignResponseWrapper() {
        // TODO: test GetCampaignResponseWrapper
    }

    /**
     * Test the property 'header'
     */
    @Test
    public void headerTest() {
        // TODO: test header
    }

    /**
     * Test the property 'body'
     */
    @Test
    public void bodyTest() {
        // TODO: test body
    }

}
