/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.shield.model;

import com.baidu.dev2.api.sdk.shield.model.ShieldClickIdType;
import com.baidu.dev2.api.sdk.shield.model.ShieldExcludeIp;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountExcludeIpType
 */
public class AccountExcludeIpTypeTest {
    private final AccountExcludeIpType model = new AccountExcludeIpType();

    /**
     * Model tests for AccountExcludeIpType
     */
    @Test
    public void testAccountExcludeIpType() {
        // TODO: test AccountExcludeIpType
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'shieldExcludeIp'
     */
    @Test
    public void shieldExcludeIpTest() {
        // TODO: test shieldExcludeIp
    }

    /**
     * Test the property 'shieldClickIdStatus'
     */
    @Test
    public void shieldClickIdStatusTest() {
        // TODO: test shieldClickIdStatus
    }

    /**
     * Test the property 'clickIds'
     */
    @Test
    public void clickIdsTest() {
        // TODO: test clickIds
    }

    /**
     * Test the property 'whiteClickIds'
     */
    @Test
    public void whiteClickIdsTest() {
        // TODO: test whiteClickIds
    }

    /**
     * Test the property 'excludeIpAddTime'
     */
    @Test
    public void excludeIpAddTimeTest() {
        // TODO: test excludeIpAddTime
    }

}
