/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 * The version of the OpenAPI document: 1.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.searchfeed.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RecmWordsFeedRequest
 */
public class RecmWordsFeedRequestTest {
    private final RecmWordsFeedRequest model = new RecmWordsFeedRequest();

    /**
     * Model tests for RecmWordsFeedRequest
     */
    @Test
    public void testRecmWordsFeedRequest() {
        // TODO: test RecmWordsFeedRequest
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'planid'
     */
    @Test
    public void planidTest() {
        // TODO: test planid
    }

    /**
     * Test the property 'unitid'
     */
    @Test
    public void unitidTest() {
        // TODO: test unitid
    }

}
