/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.danubecreativegroup.model;

import com.baidu.dev2.api.sdk.danubecreativegroup.model.Plas;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DanubePlasCreative
 */
public class DanubePlasCreativeTest {
    private final DanubePlasCreative model = new DanubePlasCreative();

    /**
     * Model tests for DanubePlasCreative
     */
    @Test
    public void testDanubePlasCreative() {
        // TODO: test DanubePlasCreative
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'mtId'
     */
    @Test
    public void mtIdTest() {
        // TODO: test mtId
    }

    /**
     * Test the property 'cnName'
     */
    @Test
    public void cnNameTest() {
        // TODO: test cnName
    }

    /**
     * Test the property 'enName'
     */
    @Test
    public void enNameTest() {
        // TODO: test enName
    }

    /**
     * Test the property 'style'
     */
    @Test
    public void styleTest() {
        // TODO: test style
    }

}
