/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.feeddiagnosis.model;

import java.util.Objects;
import java.util.Arrays;
import com.baidu.dev2.api.sdk.feeddiagnosis.model.AdviceType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TargetDiagnosisRes
 */
@JsonPropertyOrder({
  TargetDiagnosisRes.JSON_PROPERTY_TARGET_INFO,
  TargetDiagnosisRes.JSON_PROPERTY_TARGET_DESC,
  TargetDiagnosisRes.JSON_PROPERTY_TARGET_TRADE_RANK,
  TargetDiagnosisRes.JSON_PROPERTY_ADVICES
})
@JsonTypeName("TargetDiagnosisRes")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TargetDiagnosisRes {
  public static final String JSON_PROPERTY_TARGET_INFO = "targetInfo";
  private String targetInfo;

  public static final String JSON_PROPERTY_TARGET_DESC = "targetDesc";
  private String targetDesc;

  public static final String JSON_PROPERTY_TARGET_TRADE_RANK = "targetTradeRank";
  private Double targetTradeRank;

  public static final String JSON_PROPERTY_ADVICES = "advices";
  private List<AdviceType> advices = null;

  public TargetDiagnosisRes() { 
  }

  public TargetDiagnosisRes targetInfo(String targetInfo) {
    
    this.targetInfo = targetInfo;
    return this;
  }

   /**
   * Get targetInfo
   * @return targetInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TARGET_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTargetInfo() {
    return targetInfo;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetInfo(String targetInfo) {
    this.targetInfo = targetInfo;
  }


  public TargetDiagnosisRes targetDesc(String targetDesc) {
    
    this.targetDesc = targetDesc;
    return this;
  }

   /**
   * Get targetDesc
   * @return targetDesc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TARGET_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTargetDesc() {
    return targetDesc;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetDesc(String targetDesc) {
    this.targetDesc = targetDesc;
  }


  public TargetDiagnosisRes targetTradeRank(Double targetTradeRank) {
    
    this.targetTradeRank = targetTradeRank;
    return this;
  }

   /**
   * Get targetTradeRank
   * @return targetTradeRank
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TARGET_TRADE_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTargetTradeRank() {
    return targetTradeRank;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_TRADE_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetTradeRank(Double targetTradeRank) {
    this.targetTradeRank = targetTradeRank;
  }


  public TargetDiagnosisRes advices(List<AdviceType> advices) {
    
    this.advices = advices;
    return this;
  }

  public TargetDiagnosisRes addAdvicesItem(AdviceType advicesItem) {
    if (this.advices == null) {
      this.advices = new ArrayList<>();
    }
    this.advices.add(advicesItem);
    return this;
  }

   /**
   * Get advices
   * @return advices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AdviceType> getAdvices() {
    return advices;
  }


  @JsonProperty(JSON_PROPERTY_ADVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdvices(List<AdviceType> advices) {
    this.advices = advices;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TargetDiagnosisRes targetDiagnosisRes = (TargetDiagnosisRes) o;
    return Objects.equals(this.targetInfo, targetDiagnosisRes.targetInfo) &&
        Objects.equals(this.targetDesc, targetDiagnosisRes.targetDesc) &&
        Objects.equals(this.targetTradeRank, targetDiagnosisRes.targetTradeRank) &&
        Objects.equals(this.advices, targetDiagnosisRes.advices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetInfo, targetDesc, targetTradeRank, advices);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TargetDiagnosisRes {\n");
    sb.append("    targetInfo: ").append(toIndentedString(targetInfo)).append("\n");
    sb.append("    targetDesc: ").append(toIndentedString(targetDesc)).append("\n");
    sb.append("    targetTradeRank: ").append(toIndentedString(targetTradeRank)).append("\n");
    sb.append("    advices: ").append(toIndentedString(advices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

