/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.advice.model;

import com.baidu.dev2.api.sdk.advice.model.FieldFilter;
import com.baidu.dev2.api.sdk.advice.model.OcpcTransTypeInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OcpcTransTypeAcceptInfo
 */
public class OcpcTransTypeAcceptInfoTest {
    private final OcpcTransTypeAcceptInfo model = new OcpcTransTypeAcceptInfo();

    /**
     * Model tests for OcpcTransTypeAcceptInfo
     */
    @Test
    public void testOcpcTransTypeAcceptInfo() {
        // TODO: test OcpcTransTypeAcceptInfo
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    public void totalCountTest() {
        // TODO: test totalCount
    }

    /**
     * Test the property 'ocpcBid'
     */
    @Test
    public void ocpcBidTest() {
        // TODO: test ocpcBid
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

}
