/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.advice.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RecommendReasonType
 */
public class RecommendReasonTypeTest {
    private final RecommendReasonType model = new RecommendReasonType();

    /**
     * Model tests for RecommendReasonType
     */
    @Test
    public void testRecommendReasonType() {
        // TODO: test RecommendReasonType
    }

    /**
     * Test the property 'reasonType'
     */
    @Test
    public void reasonTypeTest() {
        // TODO: test reasonType
    }

    /**
     * Test the property 'improveRatio'
     */
    @Test
    public void improveRatioTest() {
        // TODO: test improveRatio
    }

}
