/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.advancedsegmentbind.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiSegmentBindQueryRequest
 */
public class ApiSegmentBindQueryRequestTest {
    private final ApiSegmentBindQueryRequest model = new ApiSegmentBindQueryRequest();

    /**
     * Model tests for ApiSegmentBindQueryRequest
     */
    @Test
    public void testApiSegmentBindQueryRequest() {
        // TODO: test ApiSegmentBindQueryRequest
    }

    /**
     * Test the property 'segmentBindTypeFields'
     */
    @Test
    public void segmentBindTypeFieldsTest() {
        // TODO: test segmentBindTypeFields
    }

    /**
     * Test the property 'bindSources'
     */
    @Test
    public void bindSourcesTest() {
        // TODO: test bindSources
    }

    /**
     * Test the property 'segmentTypes'
     */
    @Test
    public void segmentTypesTest() {
        // TODO: test segmentTypes
    }

    /**
     * Test the property 'auditStatuses'
     */
    @Test
    public void auditStatusesTest() {
        // TODO: test auditStatuses
    }

    /**
     * Test the property 'pauses'
     */
    @Test
    public void pausesTest() {
        // TODO: test pauses
    }

    /**
     * Test the property 'ids'
     */
    @Test
    public void idsTest() {
        // TODO: test ids
    }

    /**
     * Test the property 'idType'
     */
    @Test
    public void idTypeTest() {
        // TODO: test idType
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'isDesc'
     */
    @Test
    public void isDescTest() {
        // TODO: test isDesc
    }

    /**
     * Test the property 'isDeletes'
     */
    @Test
    public void isDeletesTest() {
        // TODO: test isDeletes
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
