/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.materialproduct.model;

import java.util.Objects;
import java.util.Arrays;
import com.baidu.dev2.api.sdk.materialproduct.model.BindMaterialDto;
import com.baidu.dev2.api.sdk.materialproduct.model.ContentQualityDetail;
import com.baidu.dev2.api.sdk.materialproduct.model.ProductExtDto;
import com.baidu.dev2.api.sdk.materialproduct.model.ProductImage;
import com.baidu.dev2.api.sdk.materialproduct.model.ProductVideo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TeslaProductQueryResponse
 */
@JsonPropertyOrder({
  TeslaProductQueryResponse.JSON_PROPERTY_PRODUCT_ID,
  TeslaProductQueryResponse.JSON_PROPERTY_CATEGORY_ID,
  TeslaProductQueryResponse.JSON_PROPERTY_CATEGORY_NAME,
  TeslaProductQueryResponse.JSON_PROPERTY_PRODUCT_TITLE,
  TeslaProductQueryResponse.JSON_PROPERTY_DESC,
  TeslaProductQueryResponse.JSON_PROPERTY_CONTENT,
  TeslaProductQueryResponse.JSON_PROPERTY_STATUS,
  TeslaProductQueryResponse.JSON_PROPERTY_PRODUCT_SHORT_TITLE,
  TeslaProductQueryResponse.JSON_PROPERTY_IMAGE,
  TeslaProductQueryResponse.JSON_PROPERTY_PRODUCT_EXT,
  TeslaProductQueryResponse.JSON_PROPERTY_AUDIT_VERSION,
  TeslaProductQueryResponse.JSON_PROPERTY_AUDIT_PERSON,
  TeslaProductQueryResponse.JSON_PROPERTY_AUDIT_REMARK,
  TeslaProductQueryResponse.JSON_PROPERTY_AUDIT_TIME,
  TeslaProductQueryResponse.JSON_PROPERTY_CREATE_TIME,
  TeslaProductQueryResponse.JSON_PROPERTY_UPDATE_TIME,
  TeslaProductQueryResponse.JSON_PROPERTY_RANK,
  TeslaProductQueryResponse.JSON_PROPERTY_TRADE_ID,
  TeslaProductQueryResponse.JSON_PROPERTY_VIDEO,
  TeslaProductQueryResponse.JSON_PROPERTY_QUALITY_STATUS,
  TeslaProductQueryResponse.JSON_PROPERTY_QUALITY_SCORE,
  TeslaProductQueryResponse.JSON_PROPERTY_QUALITY_DETAIL,
  TeslaProductQueryResponse.JSON_PROPERTY_BIND_MATERIAL,
  TeslaProductQueryResponse.JSON_PROPERTY_DATA_VERSION,
  TeslaProductQueryResponse.JSON_PROPERTY_REAUDIT_STATUS,
  TeslaProductQueryResponse.JSON_PROPERTY_CONTENT_QUALITY_STATUS,
  TeslaProductQueryResponse.JSON_PROPERTY_CONTENT_QUALITY_DETAIL,
  TeslaProductQueryResponse.JSON_PROPERTY_HUMAN_AUDIT
})
@JsonTypeName("TeslaProductQueryResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TeslaProductQueryResponse {
  public static final String JSON_PROPERTY_PRODUCT_ID = "productId";
  private Long productId;

  public static final String JSON_PROPERTY_CATEGORY_ID = "categoryId";
  private Long categoryId;

  public static final String JSON_PROPERTY_CATEGORY_NAME = "categoryName";
  private String categoryName;

  public static final String JSON_PROPERTY_PRODUCT_TITLE = "productTitle";
  private String productTitle;

  public static final String JSON_PROPERTY_DESC = "desc";
  private String desc;

  public static final String JSON_PROPERTY_CONTENT = "content";
  private String content;

  public static final String JSON_PROPERTY_STATUS = "status";
  private Integer status;

  public static final String JSON_PROPERTY_PRODUCT_SHORT_TITLE = "productShortTitle";
  private String productShortTitle;

  public static final String JSON_PROPERTY_IMAGE = "image";
  private List<ProductImage> image = null;

  public static final String JSON_PROPERTY_PRODUCT_EXT = "productExt";
  private ProductExtDto productExt;

  public static final String JSON_PROPERTY_AUDIT_VERSION = "auditVersion";
  private Integer auditVersion;

  public static final String JSON_PROPERTY_AUDIT_PERSON = "auditPerson";
  private Long auditPerson;

  public static final String JSON_PROPERTY_AUDIT_REMARK = "auditRemark";
  private String auditRemark;

  public static final String JSON_PROPERTY_AUDIT_TIME = "auditTime";
  private String auditTime;

  public static final String JSON_PROPERTY_CREATE_TIME = "createTime";
  private String createTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "updateTime";
  private String updateTime;

  public static final String JSON_PROPERTY_RANK = "rank";
  private Integer rank;

  public static final String JSON_PROPERTY_TRADE_ID = "tradeId";
  private Long tradeId;

  public static final String JSON_PROPERTY_VIDEO = "video";
  private List<ProductVideo> video = null;

  public static final String JSON_PROPERTY_QUALITY_STATUS = "qualityStatus";
  private Integer qualityStatus;

  public static final String JSON_PROPERTY_QUALITY_SCORE = "qualityScore";
  private Long qualityScore;

  public static final String JSON_PROPERTY_QUALITY_DETAIL = "qualityDetail";
  private String qualityDetail;

  public static final String JSON_PROPERTY_BIND_MATERIAL = "bindMaterial";
  private List<BindMaterialDto> bindMaterial = null;

  public static final String JSON_PROPERTY_DATA_VERSION = "dataVersion";
  private Integer dataVersion;

  public static final String JSON_PROPERTY_REAUDIT_STATUS = "reauditStatus";
  private Integer reauditStatus;

  public static final String JSON_PROPERTY_CONTENT_QUALITY_STATUS = "contentQualityStatus";
  private Integer contentQualityStatus;

  public static final String JSON_PROPERTY_CONTENT_QUALITY_DETAIL = "contentQualityDetail";
  private ContentQualityDetail contentQualityDetail;

  public static final String JSON_PROPERTY_HUMAN_AUDIT = "humanAudit";
  private Integer humanAudit;

  public TeslaProductQueryResponse() { 
  }

  public TeslaProductQueryResponse productId(Long productId) {
    
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductId(Long productId) {
    this.productId = productId;
  }


  public TeslaProductQueryResponse categoryId(Long categoryId) {
    
    this.categoryId = categoryId;
    return this;
  }

   /**
   * Get categoryId
   * @return categoryId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATEGORY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCategoryId() {
    return categoryId;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategoryId(Long categoryId) {
    this.categoryId = categoryId;
  }


  public TeslaProductQueryResponse categoryName(String categoryName) {
    
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Get categoryName
   * @return categoryName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCategoryName() {
    return categoryName;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }


  public TeslaProductQueryResponse productTitle(String productTitle) {
    
    this.productTitle = productTitle;
    return this;
  }

   /**
   * Get productTitle
   * @return productTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductTitle() {
    return productTitle;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductTitle(String productTitle) {
    this.productTitle = productTitle;
  }


  public TeslaProductQueryResponse desc(String desc) {
    
    this.desc = desc;
    return this;
  }

   /**
   * Get desc
   * @return desc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDesc() {
    return desc;
  }


  @JsonProperty(JSON_PROPERTY_DESC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDesc(String desc) {
    this.desc = desc;
  }


  public TeslaProductQueryResponse content(String content) {
    
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContent() {
    return content;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(String content) {
    this.content = content;
  }


  public TeslaProductQueryResponse status(Integer status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(Integer status) {
    this.status = status;
  }


  public TeslaProductQueryResponse productShortTitle(String productShortTitle) {
    
    this.productShortTitle = productShortTitle;
    return this;
  }

   /**
   * Get productShortTitle
   * @return productShortTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_SHORT_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductShortTitle() {
    return productShortTitle;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_SHORT_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductShortTitle(String productShortTitle) {
    this.productShortTitle = productShortTitle;
  }


  public TeslaProductQueryResponse image(List<ProductImage> image) {
    
    this.image = image;
    return this;
  }

  public TeslaProductQueryResponse addImageItem(ProductImage imageItem) {
    if (this.image == null) {
      this.image = new ArrayList<>();
    }
    this.image.add(imageItem);
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ProductImage> getImage() {
    return image;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImage(List<ProductImage> image) {
    this.image = image;
  }


  public TeslaProductQueryResponse productExt(ProductExtDto productExt) {
    
    this.productExt = productExt;
    return this;
  }

   /**
   * Get productExt
   * @return productExt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_EXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProductExtDto getProductExt() {
    return productExt;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_EXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductExt(ProductExtDto productExt) {
    this.productExt = productExt;
  }


  public TeslaProductQueryResponse auditVersion(Integer auditVersion) {
    
    this.auditVersion = auditVersion;
    return this;
  }

   /**
   * Get auditVersion
   * @return auditVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDIT_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAuditVersion() {
    return auditVersion;
  }


  @JsonProperty(JSON_PROPERTY_AUDIT_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuditVersion(Integer auditVersion) {
    this.auditVersion = auditVersion;
  }


  public TeslaProductQueryResponse auditPerson(Long auditPerson) {
    
    this.auditPerson = auditPerson;
    return this;
  }

   /**
   * Get auditPerson
   * @return auditPerson
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDIT_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAuditPerson() {
    return auditPerson;
  }


  @JsonProperty(JSON_PROPERTY_AUDIT_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuditPerson(Long auditPerson) {
    this.auditPerson = auditPerson;
  }


  public TeslaProductQueryResponse auditRemark(String auditRemark) {
    
    this.auditRemark = auditRemark;
    return this;
  }

   /**
   * Get auditRemark
   * @return auditRemark
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDIT_REMARK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuditRemark() {
    return auditRemark;
  }


  @JsonProperty(JSON_PROPERTY_AUDIT_REMARK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuditRemark(String auditRemark) {
    this.auditRemark = auditRemark;
  }


  public TeslaProductQueryResponse auditTime(String auditTime) {
    
    this.auditTime = auditTime;
    return this;
  }

   /**
   * Get auditTime
   * @return auditTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDIT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuditTime() {
    return auditTime;
  }


  @JsonProperty(JSON_PROPERTY_AUDIT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuditTime(String auditTime) {
    this.auditTime = auditTime;
  }


  public TeslaProductQueryResponse createTime(String createTime) {
    
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreateTime() {
    return createTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }


  public TeslaProductQueryResponse updateTime(String updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  public TeslaProductQueryResponse rank(Integer rank) {
    
    this.rank = rank;
    return this;
  }

   /**
   * Get rank
   * @return rank
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRank() {
    return rank;
  }


  @JsonProperty(JSON_PROPERTY_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRank(Integer rank) {
    this.rank = rank;
  }


  public TeslaProductQueryResponse tradeId(Long tradeId) {
    
    this.tradeId = tradeId;
    return this;
  }

   /**
   * Get tradeId
   * @return tradeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRADE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTradeId() {
    return tradeId;
  }


  @JsonProperty(JSON_PROPERTY_TRADE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradeId(Long tradeId) {
    this.tradeId = tradeId;
  }


  public TeslaProductQueryResponse video(List<ProductVideo> video) {
    
    this.video = video;
    return this;
  }

  public TeslaProductQueryResponse addVideoItem(ProductVideo videoItem) {
    if (this.video == null) {
      this.video = new ArrayList<>();
    }
    this.video.add(videoItem);
    return this;
  }

   /**
   * Get video
   * @return video
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VIDEO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ProductVideo> getVideo() {
    return video;
  }


  @JsonProperty(JSON_PROPERTY_VIDEO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideo(List<ProductVideo> video) {
    this.video = video;
  }


  public TeslaProductQueryResponse qualityStatus(Integer qualityStatus) {
    
    this.qualityStatus = qualityStatus;
    return this;
  }

   /**
   * Get qualityStatus
   * @return qualityStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUALITY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQualityStatus() {
    return qualityStatus;
  }


  @JsonProperty(JSON_PROPERTY_QUALITY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualityStatus(Integer qualityStatus) {
    this.qualityStatus = qualityStatus;
  }


  public TeslaProductQueryResponse qualityScore(Long qualityScore) {
    
    this.qualityScore = qualityScore;
    return this;
  }

   /**
   * Get qualityScore
   * @return qualityScore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUALITY_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getQualityScore() {
    return qualityScore;
  }


  @JsonProperty(JSON_PROPERTY_QUALITY_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualityScore(Long qualityScore) {
    this.qualityScore = qualityScore;
  }


  public TeslaProductQueryResponse qualityDetail(String qualityDetail) {
    
    this.qualityDetail = qualityDetail;
    return this;
  }

   /**
   * Get qualityDetail
   * @return qualityDetail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUALITY_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQualityDetail() {
    return qualityDetail;
  }


  @JsonProperty(JSON_PROPERTY_QUALITY_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualityDetail(String qualityDetail) {
    this.qualityDetail = qualityDetail;
  }


  public TeslaProductQueryResponse bindMaterial(List<BindMaterialDto> bindMaterial) {
    
    this.bindMaterial = bindMaterial;
    return this;
  }

  public TeslaProductQueryResponse addBindMaterialItem(BindMaterialDto bindMaterialItem) {
    if (this.bindMaterial == null) {
      this.bindMaterial = new ArrayList<>();
    }
    this.bindMaterial.add(bindMaterialItem);
    return this;
  }

   /**
   * Get bindMaterial
   * @return bindMaterial
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BIND_MATERIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BindMaterialDto> getBindMaterial() {
    return bindMaterial;
  }


  @JsonProperty(JSON_PROPERTY_BIND_MATERIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBindMaterial(List<BindMaterialDto> bindMaterial) {
    this.bindMaterial = bindMaterial;
  }


  public TeslaProductQueryResponse dataVersion(Integer dataVersion) {
    
    this.dataVersion = dataVersion;
    return this;
  }

   /**
   * Get dataVersion
   * @return dataVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDataVersion() {
    return dataVersion;
  }


  @JsonProperty(JSON_PROPERTY_DATA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataVersion(Integer dataVersion) {
    this.dataVersion = dataVersion;
  }


  public TeslaProductQueryResponse reauditStatus(Integer reauditStatus) {
    
    this.reauditStatus = reauditStatus;
    return this;
  }

   /**
   * Get reauditStatus
   * @return reauditStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REAUDIT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getReauditStatus() {
    return reauditStatus;
  }


  @JsonProperty(JSON_PROPERTY_REAUDIT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReauditStatus(Integer reauditStatus) {
    this.reauditStatus = reauditStatus;
  }


  public TeslaProductQueryResponse contentQualityStatus(Integer contentQualityStatus) {
    
    this.contentQualityStatus = contentQualityStatus;
    return this;
  }

   /**
   * Get contentQualityStatus
   * @return contentQualityStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTENT_QUALITY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getContentQualityStatus() {
    return contentQualityStatus;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_QUALITY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentQualityStatus(Integer contentQualityStatus) {
    this.contentQualityStatus = contentQualityStatus;
  }


  public TeslaProductQueryResponse contentQualityDetail(ContentQualityDetail contentQualityDetail) {
    
    this.contentQualityDetail = contentQualityDetail;
    return this;
  }

   /**
   * Get contentQualityDetail
   * @return contentQualityDetail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTENT_QUALITY_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ContentQualityDetail getContentQualityDetail() {
    return contentQualityDetail;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_QUALITY_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentQualityDetail(ContentQualityDetail contentQualityDetail) {
    this.contentQualityDetail = contentQualityDetail;
  }


  public TeslaProductQueryResponse humanAudit(Integer humanAudit) {
    
    this.humanAudit = humanAudit;
    return this;
  }

   /**
   * Get humanAudit
   * @return humanAudit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HUMAN_AUDIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHumanAudit() {
    return humanAudit;
  }


  @JsonProperty(JSON_PROPERTY_HUMAN_AUDIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHumanAudit(Integer humanAudit) {
    this.humanAudit = humanAudit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeslaProductQueryResponse teslaProductQueryResponse = (TeslaProductQueryResponse) o;
    return Objects.equals(this.productId, teslaProductQueryResponse.productId) &&
        Objects.equals(this.categoryId, teslaProductQueryResponse.categoryId) &&
        Objects.equals(this.categoryName, teslaProductQueryResponse.categoryName) &&
        Objects.equals(this.productTitle, teslaProductQueryResponse.productTitle) &&
        Objects.equals(this.desc, teslaProductQueryResponse.desc) &&
        Objects.equals(this.content, teslaProductQueryResponse.content) &&
        Objects.equals(this.status, teslaProductQueryResponse.status) &&
        Objects.equals(this.productShortTitle, teslaProductQueryResponse.productShortTitle) &&
        Objects.equals(this.image, teslaProductQueryResponse.image) &&
        Objects.equals(this.productExt, teslaProductQueryResponse.productExt) &&
        Objects.equals(this.auditVersion, teslaProductQueryResponse.auditVersion) &&
        Objects.equals(this.auditPerson, teslaProductQueryResponse.auditPerson) &&
        Objects.equals(this.auditRemark, teslaProductQueryResponse.auditRemark) &&
        Objects.equals(this.auditTime, teslaProductQueryResponse.auditTime) &&
        Objects.equals(this.createTime, teslaProductQueryResponse.createTime) &&
        Objects.equals(this.updateTime, teslaProductQueryResponse.updateTime) &&
        Objects.equals(this.rank, teslaProductQueryResponse.rank) &&
        Objects.equals(this.tradeId, teslaProductQueryResponse.tradeId) &&
        Objects.equals(this.video, teslaProductQueryResponse.video) &&
        Objects.equals(this.qualityStatus, teslaProductQueryResponse.qualityStatus) &&
        Objects.equals(this.qualityScore, teslaProductQueryResponse.qualityScore) &&
        Objects.equals(this.qualityDetail, teslaProductQueryResponse.qualityDetail) &&
        Objects.equals(this.bindMaterial, teslaProductQueryResponse.bindMaterial) &&
        Objects.equals(this.dataVersion, teslaProductQueryResponse.dataVersion) &&
        Objects.equals(this.reauditStatus, teslaProductQueryResponse.reauditStatus) &&
        Objects.equals(this.contentQualityStatus, teslaProductQueryResponse.contentQualityStatus) &&
        Objects.equals(this.contentQualityDetail, teslaProductQueryResponse.contentQualityDetail) &&
        Objects.equals(this.humanAudit, teslaProductQueryResponse.humanAudit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, categoryId, categoryName, productTitle, desc, content, status, productShortTitle, image, productExt, auditVersion, auditPerson, auditRemark, auditTime, createTime, updateTime, rank, tradeId, video, qualityStatus, qualityScore, qualityDetail, bindMaterial, dataVersion, reauditStatus, contentQualityStatus, contentQualityDetail, humanAudit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeslaProductQueryResponse {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    productTitle: ").append(toIndentedString(productTitle)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    productShortTitle: ").append(toIndentedString(productShortTitle)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    productExt: ").append(toIndentedString(productExt)).append("\n");
    sb.append("    auditVersion: ").append(toIndentedString(auditVersion)).append("\n");
    sb.append("    auditPerson: ").append(toIndentedString(auditPerson)).append("\n");
    sb.append("    auditRemark: ").append(toIndentedString(auditRemark)).append("\n");
    sb.append("    auditTime: ").append(toIndentedString(auditTime)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    tradeId: ").append(toIndentedString(tradeId)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("    qualityStatus: ").append(toIndentedString(qualityStatus)).append("\n");
    sb.append("    qualityScore: ").append(toIndentedString(qualityScore)).append("\n");
    sb.append("    qualityDetail: ").append(toIndentedString(qualityDetail)).append("\n");
    sb.append("    bindMaterial: ").append(toIndentedString(bindMaterial)).append("\n");
    sb.append("    dataVersion: ").append(toIndentedString(dataVersion)).append("\n");
    sb.append("    reauditStatus: ").append(toIndentedString(reauditStatus)).append("\n");
    sb.append("    contentQualityStatus: ").append(toIndentedString(contentQualityStatus)).append("\n");
    sb.append("    contentQualityDetail: ").append(toIndentedString(contentQualityDetail)).append("\n");
    sb.append("    humanAudit: ").append(toIndentedString(humanAudit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

