# coding: utf-8

# flake8: noqa
"""
    dev2 api schema

    'dev2.baidu.com' api schema  # noqa: E501

Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from baiduads.appprocess.model.app_info_item import AppInfoItem
from baiduads.appprocess.model.app_info_list_type import AppInfoListType
from baiduads.appprocess.model.appinfo_condition_request import AppinfoConditionRequest
from baiduads.appprocess.model.get_app_list_request_wrapper import GetAppListRequestWrapper
from baiduads.appprocess.model.get_app_list_response_wrapper import GetAppListResponseWrapper
from baiduads.appprocess.model.get_app_list_response_wrapper_body import GetAppListResponseWrapperBody
