/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.adgroupimagesegmentbind.model;

import com.baidu.dev2.api.sdk.adgroupimagesegmentbind.model.AdgroupImageSegmentBindType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddAdgroupImageSegmentBindResponseWrapperBody
 */
public class AddAdgroupImageSegmentBindResponseWrapperBodyTest {
    private final AddAdgroupImageSegmentBindResponseWrapperBody model = new AddAdgroupImageSegmentBindResponseWrapperBody();

    /**
     * Model tests for AddAdgroupImageSegmentBindResponseWrapperBody
     */
    @Test
    public void testAddAdgroupImageSegmentBindResponseWrapperBody() {
        // TODO: test AddAdgroupImageSegmentBindResponseWrapperBody
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
