/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.fluctuationanalysis.model;

import java.util.Objects;
import java.util.Arrays;
import com.baidu.dev2.api.sdk.fluctuationanalysis.model.FluctuationKeywordsType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FluctuationAnalysisDetailType
 */
@JsonPropertyOrder({
  FluctuationAnalysisDetailType.JSON_PROPERTY_DETAILS,
  FluctuationAnalysisDetailType.JSON_PROPERTY_DESCRIPTION,
  FluctuationAnalysisDetailType.JSON_PROPERTY_ADVICE_ID,
  FluctuationAnalysisDetailType.JSON_PROPERTY_TOP_KEYWORDS
})
@JsonTypeName("FluctuationAnalysisDetailType")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FluctuationAnalysisDetailType {
  public static final String JSON_PROPERTY_DETAILS = "details";
  private List<FluctuationAnalysisDetailType> details = null;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ADVICE_ID = "adviceId";
  private Long adviceId;

  public static final String JSON_PROPERTY_TOP_KEYWORDS = "topKeywords";
  private List<FluctuationKeywordsType> topKeywords = null;

  public FluctuationAnalysisDetailType() { 
  }

  public FluctuationAnalysisDetailType details(List<FluctuationAnalysisDetailType> details) {
    
    this.details = details;
    return this;
  }

  public FluctuationAnalysisDetailType addDetailsItem(FluctuationAnalysisDetailType detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FluctuationAnalysisDetailType> getDetails() {
    return details;
  }


  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetails(List<FluctuationAnalysisDetailType> details) {
    this.details = details;
  }


  public FluctuationAnalysisDetailType description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public FluctuationAnalysisDetailType adviceId(Long adviceId) {
    
    this.adviceId = adviceId;
    return this;
  }

   /**
   * Get adviceId
   * @return adviceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAdviceId() {
    return adviceId;
  }


  @JsonProperty(JSON_PROPERTY_ADVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdviceId(Long adviceId) {
    this.adviceId = adviceId;
  }


  public FluctuationAnalysisDetailType topKeywords(List<FluctuationKeywordsType> topKeywords) {
    
    this.topKeywords = topKeywords;
    return this;
  }

  public FluctuationAnalysisDetailType addTopKeywordsItem(FluctuationKeywordsType topKeywordsItem) {
    if (this.topKeywords == null) {
      this.topKeywords = new ArrayList<>();
    }
    this.topKeywords.add(topKeywordsItem);
    return this;
  }

   /**
   * Get topKeywords
   * @return topKeywords
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOP_KEYWORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FluctuationKeywordsType> getTopKeywords() {
    return topKeywords;
  }


  @JsonProperty(JSON_PROPERTY_TOP_KEYWORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopKeywords(List<FluctuationKeywordsType> topKeywords) {
    this.topKeywords = topKeywords;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FluctuationAnalysisDetailType fluctuationAnalysisDetailType = (FluctuationAnalysisDetailType) o;
    return Objects.equals(this.details, fluctuationAnalysisDetailType.details) &&
        Objects.equals(this.description, fluctuationAnalysisDetailType.description) &&
        Objects.equals(this.adviceId, fluctuationAnalysisDetailType.adviceId) &&
        Objects.equals(this.topKeywords, fluctuationAnalysisDetailType.topKeywords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, description, adviceId, topKeywords);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FluctuationAnalysisDetailType {\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    adviceId: ").append(toIndentedString(adviceId)).append("\n");
    sb.append("    topKeywords: ").append(toIndentedString(topKeywords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

