/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.appcenterpackage.model;

import java.util.Objects;
import java.util.Arrays;
import com.baidu.dev2.api.sdk.appcenterpackage.model.AuditDetail;
import com.baidu.dev2.api.sdk.appcenterpackage.model.ImageDetail;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AuditInfo
 */
@JsonPropertyOrder({
  AuditInfo.JSON_PROPERTY_IMAGE_DETAILS,
  AuditInfo.JSON_PROPERTY_AUDIT_DETAILS
})
@JsonTypeName("AuditInfo")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AuditInfo {
  public static final String JSON_PROPERTY_IMAGE_DETAILS = "imageDetails";
  private List<ImageDetail> imageDetails = null;

  public static final String JSON_PROPERTY_AUDIT_DETAILS = "auditDetails";
  private List<AuditDetail> auditDetails = null;

  public AuditInfo() { 
  }

  public AuditInfo imageDetails(List<ImageDetail> imageDetails) {
    
    this.imageDetails = imageDetails;
    return this;
  }

  public AuditInfo addImageDetailsItem(ImageDetail imageDetailsItem) {
    if (this.imageDetails == null) {
      this.imageDetails = new ArrayList<>();
    }
    this.imageDetails.add(imageDetailsItem);
    return this;
  }

   /**
   * Get imageDetails
   * @return imageDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IMAGE_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ImageDetail> getImageDetails() {
    return imageDetails;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImageDetails(List<ImageDetail> imageDetails) {
    this.imageDetails = imageDetails;
  }


  public AuditInfo auditDetails(List<AuditDetail> auditDetails) {
    
    this.auditDetails = auditDetails;
    return this;
  }

  public AuditInfo addAuditDetailsItem(AuditDetail auditDetailsItem) {
    if (this.auditDetails == null) {
      this.auditDetails = new ArrayList<>();
    }
    this.auditDetails.add(auditDetailsItem);
    return this;
  }

   /**
   * Get auditDetails
   * @return auditDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDIT_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AuditDetail> getAuditDetails() {
    return auditDetails;
  }


  @JsonProperty(JSON_PROPERTY_AUDIT_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuditDetails(List<AuditDetail> auditDetails) {
    this.auditDetails = auditDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditInfo auditInfo = (AuditInfo) o;
    return Objects.equals(this.imageDetails, auditInfo.imageDetails) &&
        Objects.equals(this.auditDetails, auditInfo.auditDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageDetails, auditDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditInfo {\n");
    sb.append("    imageDetails: ").append(toIndentedString(imageDetails)).append("\n");
    sb.append("    auditDetails: ").append(toIndentedString(auditDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

