/*
 * dev2 api schema
 * 'dev2.baidu.com' api schema
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidu.dev2.api.sdk.bmcdistribution.api;

import com.baidu.dev2.api.sdk.invoke.ApiException;
import com.baidu.dev2.api.sdk.bmcdistribution.model.GetCatalogRequestWrapper;
import com.baidu.dev2.api.sdk.bmcdistribution.model.GetCatalogResponseWrapper;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BmcDistributionService
 */
@Ignore
public class BmcDistributionServiceTest {

    private final BmcDistributionService api = new BmcDistributionService();

    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCatalogTest() throws ApiException {
        GetCatalogRequestWrapper getCatalogRequestWrapper = null;
        GetCatalogResponseWrapper response = api.getCatalog(getCatalogRequestWrapper);

        // TODO: test validations
    }
}
